-- 司机安全培训考试模块 PostgreSQL DDL
-- 说明：
-- 1. 所有业务表主键统一为 id bigint generated by default as identity。
-- 2. 关联字段仅建立普通索引，不创建外键约束。
-- 3. 枚举字段使用 varchar 存储，枚举定义写入 sys_dict_type / sys_dict_item。
-- 4. 所有业务表使用 is_del 标识逻辑删除，false 表示未删除，true 表示已删除。

BEGIN;

CREATE TABLE public.training_course (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    course_name varchar(200) NOT NULL,
    training_type varchar(50) NOT NULL,
    introduction text,
    planned_learning_seconds integer NOT NULL,
    video_file_id varchar(128) NOT NULL,
    video_duration_seconds integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    is_locked boolean NOT NULL DEFAULT false,
    created_by varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar(64) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_training_course_learning_seconds_nonnegative
        CHECK (planned_learning_seconds >= 0 AND video_duration_seconds >= 0),
    CONSTRAINT ck_training_course_duration_consistent
        CHECK (planned_learning_seconds = video_duration_seconds)
);

COMMENT ON TABLE public.training_course IS '培训视频课程';
COMMENT ON COLUMN public.training_course.id IS '主键，自增';
COMMENT ON COLUMN public.training_course.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.training_course.course_name IS '课程名称';
COMMENT ON COLUMN public.training_course.training_type IS '培训类型，字典：training_type';
COMMENT ON COLUMN public.training_course.introduction IS '课程简介';
COMMENT ON COLUMN public.training_course.planned_learning_seconds IS '计划学习时长，单位秒；必须与视频实际时长一致';
COMMENT ON COLUMN public.training_course.video_file_id IS '课程视频文件标识，关联系统统一文件资源';
COMMENT ON COLUMN public.training_course.video_duration_seconds IS '视频实际时长，单位秒；必须与计划学习时长一致';
COMMENT ON COLUMN public.training_course.status IS '课程状态，字典：training_course_status';
COMMENT ON COLUMN public.training_course.is_locked IS '课程核心内容是否锁定；被执行中的培训任务使用后锁定';
COMMENT ON COLUMN public.training_course.created_by IS '创建人唯一标识';
COMMENT ON COLUMN public.training_course.created_at IS '创建时间';
COMMENT ON COLUMN public.training_course.updated_by IS '最后修改人唯一标识';
COMMENT ON COLUMN public.training_course.updated_at IS '最后修改时间';



CREATE TABLE public.exam_question (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    question_type varchar(20) NOT NULL,
    question_text text NOT NULL,
    explanation text,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    created_by varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar(64) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE public.exam_question IS '考试题库题目';
COMMENT ON COLUMN public.exam_question.id IS '主键，自增';
COMMENT ON COLUMN public.exam_question.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.exam_question.question_type IS '题型，字典：exam_question_type';
COMMENT ON COLUMN public.exam_question.question_text IS '题干';
COMMENT ON COLUMN public.exam_question.explanation IS '答案解析';
COMMENT ON COLUMN public.exam_question.status IS '题目状态，字典：exam_question_status';
COMMENT ON COLUMN public.exam_question.created_by IS '创建人唯一标识';
COMMENT ON COLUMN public.exam_question.created_at IS '创建时间';
COMMENT ON COLUMN public.exam_question.updated_by IS '最后修改人唯一标识';
COMMENT ON COLUMN public.exam_question.updated_at IS '最后修改时间';


CREATE TABLE public.exam_question_option (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    question_id bigint NOT NULL,
    option_code varchar(10) NOT NULL,
    option_text text NOT NULL,
    is_correct boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL,
    CONSTRAINT uk_exam_question_option_question_code UNIQUE (question_id, option_code),
    CONSTRAINT uk_exam_question_option_question_sort UNIQUE (question_id, sort_order),
    CONSTRAINT ck_exam_question_option_sort_positive CHECK (sort_order > 0)
);

COMMENT ON TABLE public.exam_question_option IS '考试题库题目选项';
COMMENT ON COLUMN public.exam_question_option.id IS '主键，自增';
COMMENT ON COLUMN public.exam_question_option.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.exam_question_option.question_id IS '关联 exam_question.id，不创建外键';
COMMENT ON COLUMN public.exam_question_option.option_code IS '题库选项标识，如 A、B、C、D';
COMMENT ON COLUMN public.exam_question_option.option_text IS '选项内容';
COMMENT ON COLUMN public.exam_question_option.is_correct IS '是否为正确答案';
COMMENT ON COLUMN public.exam_question_option.sort_order IS '选项在题库中的默认显示顺序';

CREATE TABLE public.exam_paper (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    paper_name varchar(200) NOT NULL,
    paper_mode varchar(20) NOT NULL,
    total_score numeric(8, 2) NOT NULL,
    random_question_order boolean NOT NULL DEFAULT false,
    random_option_order boolean NOT NULL DEFAULT false,
    single_choice_count integer,
    single_choice_score numeric(8, 2),
    multiple_choice_count integer,
    multiple_choice_score numeric(8, 2),
    true_false_count integer,
    true_false_score numeric(8, 2),
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    created_by varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar(64) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE public.exam_paper IS '考试试卷';
COMMENT ON COLUMN public.exam_paper.id IS '主键，自增';
COMMENT ON COLUMN public.exam_paper.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.exam_paper.paper_name IS '试卷名称';
COMMENT ON COLUMN public.exam_paper.paper_mode IS '组卷模式，字典：exam_paper_mode';
COMMENT ON COLUMN public.exam_paper.total_score IS '试卷总分';
COMMENT ON COLUMN public.exam_paper.random_question_order IS '考试时是否随机排列题目顺序';
COMMENT ON COLUMN public.exam_paper.random_option_order IS '考试时是否随机排列选项顺序';
COMMENT ON COLUMN public.exam_paper.single_choice_count IS '随机组卷时单选题抽取数量；固定组卷时为空';
COMMENT ON COLUMN public.exam_paper.single_choice_score IS '随机组卷时每道单选题分值；固定组卷时为空';
COMMENT ON COLUMN public.exam_paper.multiple_choice_count IS '随机组卷时多选题抽取数量；固定组卷时为空';
COMMENT ON COLUMN public.exam_paper.multiple_choice_score IS '随机组卷时每道多选题分值；固定组卷时为空';
COMMENT ON COLUMN public.exam_paper.true_false_count IS '随机组卷时判断题抽取数量；固定组卷时为空';
COMMENT ON COLUMN public.exam_paper.true_false_score IS '随机组卷时每道判断题分值；固定组卷时为空';
COMMENT ON COLUMN public.exam_paper.status IS '试卷状态，字典：exam_paper_status';
COMMENT ON COLUMN public.exam_paper.created_by IS '创建人唯一标识';
COMMENT ON COLUMN public.exam_paper.created_at IS '创建时间';
COMMENT ON COLUMN public.exam_paper.updated_by IS '最后修改人唯一标识';
COMMENT ON COLUMN public.exam_paper.updated_at IS '最后修改时间';



CREATE TABLE public.exam_paper_question (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    paper_id bigint NOT NULL,
    question_id bigint NOT NULL,
    question_score numeric(8, 2) NOT NULL,
    sort_order integer NOT NULL,
    CONSTRAINT uk_exam_paper_question_paper_question UNIQUE (paper_id, question_id),
    CONSTRAINT uk_exam_paper_question_paper_sort UNIQUE (paper_id, sort_order),
    CONSTRAINT ck_exam_paper_question_score_positive CHECK (question_score > 0),
    CONSTRAINT ck_exam_paper_question_sort_positive CHECK (sort_order > 0)
);

COMMENT ON TABLE public.exam_paper_question IS '固定试卷题目明细';
COMMENT ON COLUMN public.exam_paper_question.id IS '主键，自增';
COMMENT ON COLUMN public.exam_paper_question.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.exam_paper_question.paper_id IS '关联 exam_paper.id；仅固定组卷使用，不创建外键';
COMMENT ON COLUMN public.exam_paper_question.question_id IS '关联 exam_question.id，不创建外键';
COMMENT ON COLUMN public.exam_paper_question.question_score IS '该题在试卷中的分值';
COMMENT ON COLUMN public.exam_paper_question.sort_order IS '题目在固定试卷中的默认顺序';

CREATE INDEX idx_exam_paper_question_question_id ON public.exam_paper_question (question_id);

CREATE TABLE public.training_exam (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    exam_name varchar(200) NOT NULL,
    paper_id bigint NOT NULL,
    duration_seconds integer NOT NULL,
    pass_score numeric(8, 2) NOT NULL,
    max_attempts integer NOT NULL,
    show_correct_answer boolean NOT NULL DEFAULT false,
    show_explanation boolean NOT NULL DEFAULT false,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    created_by varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar(64) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_training_exam_duration_positive CHECK (duration_seconds > 0),
    CONSTRAINT ck_training_exam_pass_score_nonnegative CHECK (pass_score >= 0),
    CONSTRAINT ck_training_exam_max_attempts_positive CHECK (max_attempts >= 1)
);

COMMENT ON TABLE public.training_exam IS '培训考试规则';
COMMENT ON COLUMN public.training_exam.id IS '主键，自增';
COMMENT ON COLUMN public.training_exam.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.training_exam.exam_name IS '考试名称';
COMMENT ON COLUMN public.training_exam.paper_id IS '关联 exam_paper.id，不创建外键';
COMMENT ON COLUMN public.training_exam.duration_seconds IS '考试时长，单位秒';
COMMENT ON COLUMN public.training_exam.pass_score IS '考试合格分数';
COMMENT ON COLUMN public.training_exam.max_attempts IS '最大允许考试次数，包含首次考试';
COMMENT ON COLUMN public.training_exam.show_correct_answer IS '考试结束后是否允许司机查看正确答案';
COMMENT ON COLUMN public.training_exam.show_explanation IS '考试结束后是否允许司机查看答案解析';
COMMENT ON COLUMN public.training_exam.status IS '考试状态，字典：training_exam_status';
COMMENT ON COLUMN public.training_exam.created_by IS '创建人唯一标识';
COMMENT ON COLUMN public.training_exam.created_at IS '创建时间';
COMMENT ON COLUMN public.training_exam.updated_by IS '最后修改人唯一标识';
COMMENT ON COLUMN public.training_exam.updated_at IS '最后修改时间';

CREATE INDEX idx_training_exam_paper_id ON public.training_exam (paper_id);

CREATE TABLE public.training_plan (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    plan_year integer NOT NULL,
    plan_name varchar(200) NOT NULL,
    start_at timestamptz NOT NULL,
    end_at timestamptz NOT NULL,
    frequency varchar(20) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'DRAFT',
    created_by varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar(64) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_training_plan_year UNIQUE (plan_year)
);

COMMENT ON TABLE public.training_plan IS '年度司机安全培训计划';
COMMENT ON COLUMN public.training_plan.id IS '主键，自增；年度培训计划唯一标识';
COMMENT ON COLUMN public.training_plan.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.training_plan.plan_year IS '培训计划所属自然年度；每个自然年度最多一个培训计划';
COMMENT ON COLUMN public.training_plan.plan_name IS '培训计划名称';
COMMENT ON COLUMN public.training_plan.start_at IS '计划开始时间';
COMMENT ON COLUMN public.training_plan.end_at IS '计划结束时间';
COMMENT ON COLUMN public.training_plan.frequency IS '培训频率，字典：training_plan_frequency';
COMMENT ON COLUMN public.training_plan.status IS '培训计划状态，字典：training_plan_status';
COMMENT ON COLUMN public.training_plan.created_by IS '创建人唯一标识';
COMMENT ON COLUMN public.training_plan.created_at IS '创建时间';
COMMENT ON COLUMN public.training_plan.updated_by IS '最后修改人唯一标识';
COMMENT ON COLUMN public.training_plan.updated_at IS '最后修改时间';


CREATE TABLE public.training_plan_employee_period (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    employee_id varchar(64) NOT NULL,
    effective_from timestamptz NOT NULL,
    effective_to timestamptz,
    created_by varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_training_plan_employee_period_range
        CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

COMMENT ON TABLE public.training_plan_employee_period IS '年度培训计划司机有效期记录';
COMMENT ON COLUMN public.training_plan_employee_period.id IS '主键，自增';
COMMENT ON COLUMN public.training_plan_employee_period.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.training_plan_employee_period.training_id IS '关联 training_plan.id，不创建外键';
COMMENT ON COLUMN public.training_plan_employee_period.employee_id IS 'VMS 司机唯一标识';
COMMENT ON COLUMN public.training_plan_employee_period.effective_from IS '司机加入培训计划的生效时间';
COMMENT ON COLUMN public.training_plan_employee_period.effective_to IS '司机退出培训计划的时间；为空表示当前有效';
COMMENT ON COLUMN public.training_plan_employee_period.created_by IS '操作人唯一标识';
COMMENT ON COLUMN public.training_plan_employee_period.created_at IS '创建时间';

CREATE INDEX idx_training_plan_employee_period_training_employee
    ON public.training_plan_employee_period (training_id, employee_id);
CREATE UNIQUE INDEX uk_training_plan_employee_period_current
    ON public.training_plan_employee_period (training_id, employee_id)
    WHERE effective_to IS NULL;

CREATE TABLE public.training_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    task_name varchar(200) NOT NULL,
    period_key varchar(20) NOT NULL,
    period_start_at timestamptz NOT NULL,
    period_end_at timestamptz NOT NULL,
    start_at timestamptz NOT NULL,
    deadline_at timestamptz NOT NULL,
    exam_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'NOT_STARTED',
    is_locked boolean NOT NULL DEFAULT false,
    created_by varchar(64) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by varchar(64) NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_training_task_training_period UNIQUE (training_id, period_key)
);

COMMENT ON TABLE public.training_task IS '月度或季度培训任务';
COMMENT ON COLUMN public.training_task.id IS '主键，自增';
COMMENT ON COLUMN public.training_task.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.training_task.training_id IS '关联 training_plan.id，不创建外键';
COMMENT ON COLUMN public.training_task.task_name IS '培训任务名称';
COMMENT ON COLUMN public.training_task.period_key IS '培训周期标识，如 2026-08、2026-Q3';
COMMENT ON COLUMN public.training_task.period_start_at IS '所属培训周期开始时间';
COMMENT ON COLUMN public.training_task.period_end_at IS '所属培训周期结束时间';
COMMENT ON COLUMN public.training_task.start_at IS '培训任务实际开始时间';
COMMENT ON COLUMN public.training_task.deadline_at IS '培训任务截止时间';
COMMENT ON COLUMN public.training_task.exam_id IS '关联 training_exam.id；一个培训任务仅关联一个考试，不创建外键';
COMMENT ON COLUMN public.training_task.status IS '任务状态，字典：training_task_status';
COMMENT ON COLUMN public.training_task.is_locked IS '任务核心配置是否锁定；开始执行后锁定';
COMMENT ON COLUMN public.training_task.created_by IS '创建人唯一标识';
COMMENT ON COLUMN public.training_task.created_at IS '创建时间';
COMMENT ON COLUMN public.training_task.updated_by IS '最后修改人唯一标识';
COMMENT ON COLUMN public.training_task.updated_at IS '最后修改时间';

CREATE INDEX idx_training_task_exam_id ON public.training_task (exam_id);

CREATE TABLE public.training_task_course (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    training_task_id bigint NOT NULL,
    course_id bigint NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_training_task_course_task_course UNIQUE (training_task_id, course_id)
);

COMMENT ON TABLE public.training_task_course IS '培训任务课程配置';
COMMENT ON COLUMN public.training_task_course.id IS '主键，自增';
COMMENT ON COLUMN public.training_task_course.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.training_task_course.training_id IS '关联 training_plan.id，冗余保存培训计划标识，不创建外键';
COMMENT ON COLUMN public.training_task_course.training_task_id IS '关联 training_task.id，不创建外键';
COMMENT ON COLUMN public.training_task_course.course_id IS '关联 training_course.id，不创建外键';
COMMENT ON COLUMN public.training_task_course.sort_order IS '课程在培训任务中的学习顺序';
COMMENT ON COLUMN public.training_task_course.created_at IS '创建时间';

CREATE INDEX idx_training_task_course_training_id ON public.training_task_course (training_id);
CREATE INDEX idx_training_task_course_course_id ON public.training_task_course (course_id);

CREATE TABLE public.training_task_employee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    training_task_id bigint NOT NULL,
    employee_id varchar(64) NOT NULL,
    is_required boolean NOT NULL DEFAULT true,
    assigned_at timestamptz NOT NULL,
    excluded_at timestamptz,
    status varchar(30) NOT NULL DEFAULT 'NOT_STARTED',
    ever_overdue boolean NOT NULL DEFAULT false,
    overdue_at timestamptz,
    first_learning_at timestamptz,
    total_learning_seconds integer NOT NULL DEFAULT 0,
    final_employee_exam_id bigint,
    final_score numeric(8, 2),
    final_passed boolean,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_training_task_employee_task_employee UNIQUE (training_task_id, employee_id)
);

COMMENT ON TABLE public.training_task_employee IS '培训任务司机执行汇总';
COMMENT ON COLUMN public.training_task_employee.id IS '主键，自增';
COMMENT ON COLUMN public.training_task_employee.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.training_task_employee.training_id IS '关联 training_plan.id，冗余保存培训计划标识，不创建外键';
COMMENT ON COLUMN public.training_task_employee.training_task_id IS '关联 training_task.id，不创建外键';
COMMENT ON COLUMN public.training_task_employee.employee_id IS 'VMS 司机唯一标识';
COMMENT ON COLUMN public.training_task_employee.is_required IS '当前是否计入该培训任务应培训人员';
COMMENT ON COLUMN public.training_task_employee.assigned_at IS '司机纳入该培训任务的时间';
COMMENT ON COLUMN public.training_task_employee.excluded_at IS '司机退出该培训任务应培训范围的时间';
COMMENT ON COLUMN public.training_task_employee.status IS '司机培训状态，字典：employee_training_task_status';
COMMENT ON COLUMN public.training_task_employee.ever_overdue IS '是否曾经发生培训逾期';
COMMENT ON COLUMN public.training_task_employee.overdue_at IS '首次发生培训逾期的时间';
COMMENT ON COLUMN public.training_task_employee.first_learning_at IS '首次开始学习的时间';
COMMENT ON COLUMN public.training_task_employee.total_learning_seconds IS '该培训任务累计有效学习时长，单位秒';
COMMENT ON COLUMN public.training_task_employee.final_employee_exam_id IS '最终有效考试记录标识，关联 employee_exam.id，不创建外键';
COMMENT ON COLUMN public.training_task_employee.final_score IS '最终考试成绩';
COMMENT ON COLUMN public.training_task_employee.final_passed IS '最终考试是否合格';
COMMENT ON COLUMN public.training_task_employee.completed_at IS '培训最终完成时间';
COMMENT ON COLUMN public.training_task_employee.created_at IS '创建时间';
COMMENT ON COLUMN public.training_task_employee.updated_at IS '最后更新时间';

CREATE INDEX idx_training_task_employee_training_id ON public.training_task_employee (training_id);
CREATE INDEX idx_training_task_employee_employee_id ON public.training_task_employee (employee_id);
CREATE INDEX idx_training_task_employee_final_exam ON public.training_task_employee (final_employee_exam_id);

CREATE TABLE public.employee_training_course_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    training_task_id bigint NOT NULL,
    employee_id varchar(64) NOT NULL,
    training_task_employee_id bigint NOT NULL,
    training_task_course_id bigint NOT NULL,
    course_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'NOT_STARTED',
    learned_position_seconds integer NOT NULL DEFAULT 0,
    effective_learning_seconds integer NOT NULL DEFAULT 0,
    started_at timestamptz,
    last_learning_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_employee_course_progress_employee_course
        UNIQUE (training_task_employee_id, training_task_course_id)
);

COMMENT ON TABLE public.employee_training_course_progress IS '司机培训任务课程学习进度';
COMMENT ON COLUMN public.employee_training_course_progress.id IS '主键，自增';
COMMENT ON COLUMN public.employee_training_course_progress.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.employee_training_course_progress.training_id IS '关联 training_plan.id，冗余保存培训计划标识，不创建外键';
COMMENT ON COLUMN public.employee_training_course_progress.training_task_id IS '关联 training_task.id，冗余保存培训任务标识，不创建外键';
COMMENT ON COLUMN public.employee_training_course_progress.employee_id IS 'VMS 司机唯一标识';
COMMENT ON COLUMN public.employee_training_course_progress.training_task_employee_id IS '关联 training_task_employee.id，不创建外键';
COMMENT ON COLUMN public.employee_training_course_progress.training_task_course_id IS '关联 training_task_course.id，不创建外键';
COMMENT ON COLUMN public.employee_training_course_progress.course_id IS '关联 training_course.id，冗余保存课程标识，不创建外键';
COMMENT ON COLUMN public.employee_training_course_progress.status IS '课程学习状态，字典：employee_course_learning_status';
COMMENT ON COLUMN public.employee_training_course_progress.learned_position_seconds IS '已确认有效学习到的视频位置，单位秒；用于学习进度和断点续播';
COMMENT ON COLUMN public.employee_training_course_progress.effective_learning_seconds IS '该课程累计有效学习时长，单位秒';
COMMENT ON COLUMN public.employee_training_course_progress.started_at IS '首次开始学习时间';
COMMENT ON COLUMN public.employee_training_course_progress.last_learning_at IS '最近一次有效学习时间';
COMMENT ON COLUMN public.employee_training_course_progress.completed_at IS '课程完成时间';
COMMENT ON COLUMN public.employee_training_course_progress.created_at IS '创建时间';
COMMENT ON COLUMN public.employee_training_course_progress.updated_at IS '最后更新时间';

CREATE INDEX idx_employee_course_progress_training_task ON public.employee_training_course_progress (training_task_id);
CREATE INDEX idx_employee_course_progress_employee ON public.employee_training_course_progress (employee_id);
CREATE INDEX idx_employee_course_progress_course ON public.employee_training_course_progress (course_id);

CREATE TABLE public.employee_exam (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    training_task_id bigint NOT NULL,
    employee_id varchar(64) NOT NULL,
    training_task_employee_id bigint NOT NULL,
    exam_id bigint NOT NULL,
    paper_id bigint NOT NULL,
    attempt_no integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'IN_PROGRESS',
    duration_seconds integer NOT NULL,
    pass_score numeric(8, 2) NOT NULL,
    max_attempts integer NOT NULL,
    show_correct_answer boolean NOT NULL,
    show_explanation boolean NOT NULL,
    started_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    submitted_at timestamptz,
    submit_type varchar(20),
    score numeric(8, 2),
    passed boolean,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_employee_exam_task_employee_attempt UNIQUE (training_task_employee_id, attempt_no)
);

COMMENT ON TABLE public.employee_exam IS '司机每次考试记录及考试规则快照';
COMMENT ON COLUMN public.employee_exam.id IS '主键，自增';
COMMENT ON COLUMN public.employee_exam.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.employee_exam.training_id IS '关联 training_plan.id，冗余保存培训计划标识，不创建外键';
COMMENT ON COLUMN public.employee_exam.training_task_id IS '关联 training_task.id，冗余保存培训任务标识，不创建外键';
COMMENT ON COLUMN public.employee_exam.employee_id IS 'VMS 司机唯一标识';
COMMENT ON COLUMN public.employee_exam.training_task_employee_id IS '关联 training_task_employee.id，不创建外键';
COMMENT ON COLUMN public.employee_exam.exam_id IS '关联 training_exam.id，不创建外键';
COMMENT ON COLUMN public.employee_exam.paper_id IS '关联 exam_paper.id，冗余保存本次考试使用的试卷标识，不创建外键';
COMMENT ON COLUMN public.employee_exam.attempt_no IS '第几次考试，从 1 开始';
COMMENT ON COLUMN public.employee_exam.status IS '考试状态，字典：employee_exam_status';
COMMENT ON COLUMN public.employee_exam.duration_seconds IS '本次考试采用的考试时长快照，单位秒';
COMMENT ON COLUMN public.employee_exam.pass_score IS '本次考试采用的合格分数快照';
COMMENT ON COLUMN public.employee_exam.max_attempts IS '本次考试采用的最大允许考试次数快照';
COMMENT ON COLUMN public.employee_exam.show_correct_answer IS '本次考试是否允许查看正确答案的规则快照';
COMMENT ON COLUMN public.employee_exam.show_explanation IS '本次考试是否允许查看答案解析的规则快照';
COMMENT ON COLUMN public.employee_exam.started_at IS '考试开始时间';
COMMENT ON COLUMN public.employee_exam.expires_at IS '本次考试截止时间';
COMMENT ON COLUMN public.employee_exam.submitted_at IS '实际提交时间';
COMMENT ON COLUMN public.employee_exam.submit_type IS '提交方式，字典：employee_exam_submit_type';
COMMENT ON COLUMN public.employee_exam.score IS '本次考试最终得分';
COMMENT ON COLUMN public.employee_exam.passed IS '本次考试是否合格';
COMMENT ON COLUMN public.employee_exam.created_at IS '创建时间';
COMMENT ON COLUMN public.employee_exam.updated_at IS '最后更新时间';

CREATE INDEX idx_employee_exam_training_task ON public.employee_exam (training_task_id);
CREATE INDEX idx_employee_exam_employee ON public.employee_exam (employee_id);
CREATE INDEX idx_employee_exam_exam_id ON public.employee_exam (exam_id);
CREATE INDEX idx_employee_exam_paper_id ON public.employee_exam (paper_id);

CREATE TABLE public.employee_exam_question (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    training_task_id bigint NOT NULL,
    employee_id varchar(64) NOT NULL,
    employee_exam_id bigint NOT NULL,
    source_question_id bigint NOT NULL,
    question_type varchar(20) NOT NULL,
    question_text text NOT NULL,
    explanation text,
    question_order integer NOT NULL,
    question_score numeric(8, 2) NOT NULL,
    is_correct boolean,
    awarded_score numeric(8, 2),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_employee_exam_question_exam_order UNIQUE (employee_exam_id, question_order)
);

COMMENT ON TABLE public.employee_exam_question IS '司机考试题目快照及判题结果';
COMMENT ON COLUMN public.employee_exam_question.id IS '主键，自增';
COMMENT ON COLUMN public.employee_exam_question.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.employee_exam_question.training_id IS '关联 training_plan.id，冗余保存培训计划标识，不创建外键';
COMMENT ON COLUMN public.employee_exam_question.training_task_id IS '关联 training_task.id，冗余保存培训任务标识，不创建外键';
COMMENT ON COLUMN public.employee_exam_question.employee_id IS 'VMS 司机唯一标识';
COMMENT ON COLUMN public.employee_exam_question.employee_exam_id IS '关联 employee_exam.id，不创建外键';
COMMENT ON COLUMN public.employee_exam_question.source_question_id IS '原题库题目标识，关联 exam_question.id；仅用于追溯，不创建外键';
COMMENT ON COLUMN public.employee_exam_question.question_type IS '本次考试时的题型快照，字典：exam_question_type';
COMMENT ON COLUMN public.employee_exam_question.question_text IS '本次考试时的题干快照';
COMMENT ON COLUMN public.employee_exam_question.explanation IS '本次考试时的答案解析快照';
COMMENT ON COLUMN public.employee_exam_question.question_order IS '本次考试中的实际题目显示顺序';
COMMENT ON COLUMN public.employee_exam_question.question_score IS '本题满分';
COMMENT ON COLUMN public.employee_exam_question.is_correct IS '本题最终是否回答正确';
COMMENT ON COLUMN public.employee_exam_question.awarded_score IS '本题实际得分';
COMMENT ON COLUMN public.employee_exam_question.created_at IS '本次考试题目生成时间';
COMMENT ON COLUMN public.employee_exam_question.updated_at IS '最后更新时间';

CREATE INDEX idx_employee_exam_question_training_task ON public.employee_exam_question (training_task_id);
CREATE INDEX idx_employee_exam_question_employee ON public.employee_exam_question (employee_id);
CREATE INDEX idx_employee_exam_question_source ON public.employee_exam_question (source_question_id);

CREATE TABLE public.employee_exam_option (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_del bool NOT NULL DEFAULT false,
    training_id bigint NOT NULL,
    training_task_id bigint NOT NULL,
    employee_id varchar(64) NOT NULL,
    employee_exam_id bigint NOT NULL,
    employee_exam_question_id bigint NOT NULL,
    source_option_id bigint NOT NULL,
    option_text text NOT NULL,
    option_order integer NOT NULL,
    is_correct boolean NOT NULL,
    is_selected boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_employee_exam_option_question_order UNIQUE (employee_exam_question_id, option_order)
);

COMMENT ON TABLE public.employee_exam_option IS '司机考试选项快照及作答结果';
COMMENT ON COLUMN public.employee_exam_option.id IS '主键，自增';
COMMENT ON COLUMN public.employee_exam_option.is_del IS '是否删除：false-未删除，true-已删除';
COMMENT ON COLUMN public.employee_exam_option.training_id IS '关联 training_plan.id，冗余保存培训计划标识，不创建外键';
COMMENT ON COLUMN public.employee_exam_option.training_task_id IS '关联 training_task.id，冗余保存培训任务标识，不创建外键';
COMMENT ON COLUMN public.employee_exam_option.employee_id IS 'VMS 司机唯一标识';
COMMENT ON COLUMN public.employee_exam_option.employee_exam_id IS '关联 employee_exam.id，冗余保存考试记录标识，不创建外键';
COMMENT ON COLUMN public.employee_exam_option.employee_exam_question_id IS '关联 employee_exam_question.id，不创建外键';
COMMENT ON COLUMN public.employee_exam_option.source_option_id IS '原题库选项标识，关联 exam_question_option.id；仅用于追溯，不创建外键';
COMMENT ON COLUMN public.employee_exam_option.option_text IS '本次考试时的选项内容快照';
COMMENT ON COLUMN public.employee_exam_option.option_order IS '本次考试中该选项的实际显示顺序；前端据此动态生成 A、B、C、D 等展示标识';
COMMENT ON COLUMN public.employee_exam_option.is_correct IS '本次考试时该选项是否属于正确答案';
COMMENT ON COLUMN public.employee_exam_option.is_selected IS '司机本次考试是否选择该选项';
COMMENT ON COLUMN public.employee_exam_option.created_at IS '本次考试选项生成时间';
COMMENT ON COLUMN public.employee_exam_option.updated_at IS '司机选择状态最后更新时间';

CREATE INDEX idx_employee_exam_option_training_task ON public.employee_exam_option (training_task_id);
CREATE INDEX idx_employee_exam_option_employee ON public.employee_exam_option (employee_id);
CREATE INDEX idx_employee_exam_option_exam ON public.employee_exam_option (employee_exam_id);
CREATE INDEX idx_employee_exam_option_source ON public.employee_exam_option (source_option_id);

-- 字典类型。
-- training_type 的枚举值未在数据模型中给出，因此仅创建字典类型，不虚构字典项。
INSERT INTO public.sys_dict_type (dict_type_code, dict_type_name, description)
VALUES
    ('training_type', '培训类型', '培训课程的业务分类；枚举值待业务补充'),
    ('training_course_status', '培训课程状态', '培训课程的生命周期状态'),
    ('exam_question_type', '考试题型', '考试题目的题型'),
    ('exam_question_status', '考试题目状态', '考试题目的生命周期状态'),
    ('exam_paper_mode', '试卷组卷模式', '试卷采用的组卷方式'),
    ('exam_paper_status', '考试试卷状态', '考试试卷的生命周期状态'),
    ('training_exam_status', '培训考试状态', '培训考试规则的生命周期状态'),
    ('training_plan_frequency', '培训计划频率', '年度培训计划的任务组织频率'),
    ('training_plan_status', '培训计划状态', '年度培训计划的生命周期状态'),
    ('training_task_status', '培训任务状态', '培训任务的执行状态'),
    ('employee_training_task_status', '司机培训状态', '司机在培训任务中的执行状态'),
    ('employee_course_learning_status', '课程学习状态', '司机对任务课程的学习状态'),
    ('employee_exam_status', '司机考试状态', '单次司机考试的状态'),
    ('employee_exam_submit_type', '考试提交方式', '单次司机考试的提交方式')
ON CONFLICT (dict_type_code) DO UPDATE
SET dict_type_name = EXCLUDED.dict_type_name,
    description = EXCLUDED.description,
    updated_at = CURRENT_TIMESTAMP,
    is_del = false;

-- 字典项。dict_type_id 与 dict_type_code 同时写入，适配现有字典表结构。
INSERT INTO public.sys_dict_item (
    dict_type_id,
    item_code,
    item_name,
    sort_no,
    description,
    dict_type_code,
    status
)
SELECT
    t.id,
    v.item_code,
    v.item_name,
    v.sort_no,
    v.description,
    v.dict_type_code,
    'ACTIVE'
FROM (
    VALUES
        ('training_course_status', 'DRAFT', '草稿', 10, '课程尚未启用'),
        ('training_course_status', 'ACTIVE', '启用', 20, '课程可被培训任务使用'),
        ('training_course_status', 'DISABLED', '停用', 30, '课程停止用于新的培训任务'),

        ('exam_question_type', 'SINGLE_CHOICE', '单选题', 10, '仅有一个正确选项'),
        ('exam_question_type', 'MULTIPLE_CHOICE', '多选题', 20, '包含多个正确选项'),
        ('exam_question_type', 'TRUE_FALSE', '判断题', 30, '判断陈述正确或错误'),

        ('exam_question_status', 'DRAFT', '草稿', 10, '题目尚未启用'),
        ('exam_question_status', 'ACTIVE', '启用', 20, '题目可用于组卷'),
        ('exam_question_status', 'DISABLED', '停用', 30, '题目停止用于新的组卷'),

        ('exam_paper_mode', 'FIXED', '固定组卷', 10, '使用预先配置的固定题目'),
        ('exam_paper_mode', 'RANDOM', '随机组卷', 20, '按题型数量和分值随机抽题'),

        ('exam_paper_status', 'DRAFT', '草稿', 10, '试卷尚未启用'),
        ('exam_paper_status', 'ACTIVE', '启用', 20, '试卷可被考试使用'),
        ('exam_paper_status', 'DISABLED', '停用', 30, '试卷停止用于新的考试'),

        ('training_exam_status', 'DRAFT', '草稿', 10, '考试尚未启用'),
        ('training_exam_status', 'ACTIVE', '启用', 20, '考试可被培训任务使用'),
        ('training_exam_status', 'DISABLED', '停用', 30, '考试停止用于新的培训任务'),

        ('training_plan_frequency', 'MONTHLY', '月度', 10, '按月度组织培训任务'),
        ('training_plan_frequency', 'QUARTERLY', '季度', 20, '按季度组织培训任务'),

        ('training_plan_status', 'DRAFT', '草稿', 10, '培训计划尚未发布'),
        ('training_plan_status', 'PUBLISHED', '已发布', 20, '培训计划已经发布'),

        ('training_task_status', 'NOT_STARTED', '未开始', 10, '培训任务尚未开始'),
        ('training_task_status', 'ACTIVE', '进行中', 20, '培训任务正在执行'),
        ('training_task_status', 'OVERDUE', '已逾期', 30, '培训任务已超过截止时间'),
        ('training_task_status', 'COMPLETED', '已完成', 40, '培训任务已经完成'),

        ('employee_training_task_status', 'NOT_STARTED', '未开始', 10, '司机尚未开始本次培训'),
        ('employee_training_task_status', 'LEARNING', '学习中', 20, '司机正在学习任务课程'),
        ('employee_training_task_status', 'READY_FOR_EXAM', '待考试', 30, '全部课程已完成，可以参加考试'),
        ('employee_training_task_status', 'EXAM_FAILED', '考试未通过', 40, '最近一次考试未通过且仍可能补考'),
        ('employee_training_task_status', 'OVERDUE', '已逾期', 50, '司机未在截止时间前完成培训'),
        ('employee_training_task_status', 'COMPLETED', '已完成', 60, '司机已经完成培训并通过考试'),

        ('employee_course_learning_status', 'NOT_STARTED', '未开始', 10, '课程尚未开始学习'),
        ('employee_course_learning_status', 'LEARNING', '学习中', 20, '课程正在学习'),
        ('employee_course_learning_status', 'COMPLETED', '已完成', 30, '课程已经完成学习'),

        ('employee_exam_status', 'IN_PROGRESS', '答题中', 10, '本次考试正在进行'),
        ('employee_exam_status', 'SUBMITTED', '已交卷', 20, '本次考试已经提交'),

        ('employee_exam_submit_type', 'MANUAL', '主动交卷', 10, '司机主动提交试卷'),
        ('employee_exam_submit_type', 'TIMEOUT', '超时交卷', 20, '考试到时由系统自动提交')
) AS v(dict_type_code, item_code, item_name, sort_no, description)
JOIN public.sys_dict_type t
  ON t.dict_type_code = v.dict_type_code
ON CONFLICT (dict_type_code, item_code) DO UPDATE
SET dict_type_id = EXCLUDED.dict_type_id,
    item_name = EXCLUDED.item_name,
    sort_no = EXCLUDED.sort_no,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP,
    is_del = false;

COMMIT;
