import type { FrameworkShellFixture } from '../types/frameworkShell'

export const frameworkShellFixture: FrameworkShellFixture = {
  productName: '陆链控制台',
  currentSystemLabel: 'TMS 运输管理',
  systems: [
    {
      id: 'platform',
      label: '平台',
      icon: 'mdi:view-dashboard-outline',
      href: '/platform/dashboard',
    },
    { id: 'iam', label: 'IAM', icon: 'mdi:account-key-outline', href: '/iam/overview' },
    { id: 'tms', label: 'TMS', icon: 'mdi:truck-delivery-outline', href: '/tms/overview' },
    { id: 'vms', label: 'VMS', icon: 'mdi:car-cog', href: '/vms/overview' },
  ],
  navigation: [
    {
      id: 'orders',
      label: '运输订单',
      icon: 'mdi:clipboard-text-outline',
      href: '/tms/orders',
    },
    {
      id: 'dispatch',
      label: '调度中心',
      icon: 'mdi:map-marker-path',
      active: true,
      expanded: true,
      children: [
        { id: 'dispatch-overview', label: '调度总览', href: '/tms/dispatch/overview' },
        { id: 'local-dispatch', label: '本地调度', href: '/tms/dispatch/local' },
        { id: 'linehaul-dispatch', label: '干线调度', href: '/tms/dispatch/linehaul' },
        { id: 'route-settings', label: '线路设置', href: '/tms/dispatch/routes' },
        { id: 'rate-estimate', label: '运价试算', href: '/tms/dispatch/rates' },
        { id: 'dispatch-parameters', label: '调度参数', href: '/tms/dispatch/parameters' },
        { id: 'transport-tasks', label: '运输任务', href: '/tms/trips', active: true },
      ],
    },
    {
      id: 'tracking',
      label: '在途跟踪',
      icon: 'mdi:routes',
      href: '/tms/tracking',
    },
  ],
  breadcrumbs: [
    { id: 'tms', label: 'TMS 运输管理' },
    { id: 'dispatch', label: '调度中心' },
    { id: 'tasks', label: '运输任务' },
  ],
  rows: [
    {
      id: '1',
      taskNo: 'TRIP-20260904-0186',
      route: '上海嘉定 → 苏州园区',
      routeType: 'local',
      planWindow: '09-04 08:30—12:00',
      vehicle: '沪A·7K218',
      dispatcher: '林嘉',
      status: 'in-transit',
    },
    {
      id: '2',
      taskNo: 'TRIP-20260904-0191',
      route: '杭州余杭 → 宁波北仑',
      routeType: 'linehaul',
      planWindow: '09-04 09:00—14:30',
      vehicle: '浙A·36M72',
      dispatcher: '周宁',
      status: 'pending',
    },
    {
      id: '3',
      taskNo: 'TRIP-20260904-0197',
      route: '南京江宁 → 合肥蜀山',
      routeType: 'linehaul',
      planWindow: '09-04 10:15—16:00',
      vehicle: '苏A·91F03',
      dispatcher: '陈曦',
      status: 'exception',
    },
    {
      id: '4',
      taskNo: 'TRIP-20260904-0203',
      route: '无锡新吴 → 常州武进',
      routeType: 'local',
      planWindow: '09-04 11:00—13:30',
      vehicle: '苏B·52Q86',
      dispatcher: '赵岚',
      status: 'completed',
    },
    {
      id: '5',
      taskNo: 'TRIP-20260904-0208',
      route: '嘉兴秀洲 → 上海青浦',
      routeType: 'local',
      planWindow: '09-04 13:20—17:10',
      vehicle: '浙F·08C16',
      dispatcher: '林嘉',
      status: 'pending',
    },
    {
      id: '6',
      taskNo: 'TRIP-20260904-0214',
      route: '苏州相城 → 南通崇川',
      routeType: 'linehaul',
      planWindow: '09-04 14:00—18:20',
      vehicle: '苏E·63N25',
      dispatcher: '周宁',
      status: 'in-transit',
    },
  ],
}
