import type {
  AccessControlFixture,
  FunctionPermissionRole,
  ResourceNode,
  UserFunctionPermissionFixture,
} from '../types/accessControl'

const baseResource = {
  routePath: '',
  component: '',
  permissionCode: '',
  icon: 'mdi:cube-outline',
  httpMethod: '',
  apiPath: '',
  isVisible: true,
  sortOrder: 10,
  status: 'ACTIVE' as const,
  remarks: '',
  isCurrentlyEffective: true,
  invalidReason: '',
  canMaintain: true,
  version: '8',
  createdAt: '2025-01-01 09:00:00',
  createdBy: 'platform-admin',
  updatedAt: '2026-09-06 16:42:18',
  updatedBy: 'platform-admin',
}

function resource(
  value: Partial<ResourceNode> &
    Pick<ResourceNode, 'id' | 'appId' | 'resourceCode' | 'resourceName' | 'resourceType'>,
): ResourceNode {
  return { ...baseResource, ...value }
}

export const accessControlFixture: AccessControlFixture = {
  tenants: [
    { id: 3, code: 'HMXTSD', name: '汉明巡天山东' },
    { id: 7, code: 'LL-HUADONG', name: '陆链华东运营中心' },
    { id: 9, code: 'LL-HUANAN', name: '陆链华南运营中心' },
  ],
  members: [
    { id: 301, code: 'HD00017', name: '林嘉', effective: true, isTenantAdmin: true, version: '18' },
    {
      id: 302,
      code: 'HD00028',
      name: '顾敏',
      effective: true,
      isTenantAdmin: false,
      version: '11',
    },
    { id: 303, code: 'HD00041', name: '沈拓', effective: true, isTenantAdmin: false, version: '7' },
    {
      id: 304,
      code: 'HD00052',
      name: '罗青',
      effective: false,
      isTenantAdmin: true,
      isLastTenantAdmin: true,
      version: '13',
    },
  ],
  roles: [
    {
      id: 501,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      roleCode: 'dispatch_manager',
      roleName: '调度经理',
      roleType: 'CUSTOM',
      sortOrder: 10,
      status: 'ACTIVE',
      description: '负责订单、线路与调度任务的日常管理。',
      remarks: '华东调度中心标准角色。',
      isCurrentlyEffective: true,
      isGroupControlled: false,
      canMaintain: true,
      version: '12',
      createdAt: '2025-04-18 09:12:30',
      updatedAt: '2026-09-06 15:32:10',
    },
    {
      id: 502,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      roleCode: 'fleet_specialist',
      roleName: '车队运营专员',
      roleType: 'CUSTOM',
      sortOrder: 20,
      status: 'ACTIVE',
      description: '维护车辆、司机和维保任务。',
      remarks: '',
      isCurrentlyEffective: true,
      isGroupControlled: false,
      canMaintain: true,
      version: '9',
      createdAt: '2025-06-22 10:21:45',
      updatedAt: '2026-09-05 17:06:34',
    },
    {
      id: 503,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      roleCode: 'group_auditor',
      roleName: '集团审计查看',
      roleType: 'CUSTOM',
      sortOrder: 30,
      status: 'ACTIVE',
      description: '跨指定 Tenant 查看运输审计数据。',
      remarks: '由集团统一维护。',
      isCurrentlyEffective: true,
      isGroupControlled: true,
      canMaintain: false,
      version: '6',
      createdAt: '2026-01-05 08:30:00',
      updatedAt: '2026-09-04 11:28:52',
    },
    {
      id: 504,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      roleCode: 'tenant_admin',
      roleName: 'Tenant 管理员',
      roleType: 'SYSTEM',
      sortOrder: 0,
      status: 'ACTIVE',
      description: '受保护的 IAM 管理身份。',
      remarks: '',
      isCurrentlyEffective: true,
      isGroupControlled: false,
      canMaintain: false,
      version: '4',
      createdAt: '2025-01-01 00:00:00',
      updatedAt: '2026-08-28 12:10:00',
    },
    {
      id: 505,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      roleCode: 'temporary_dispatch',
      roleName: '临时调度员',
      roleType: 'CUSTOM',
      sortOrder: 90,
      status: 'DISABLED',
      description: '历史临时角色，配置与分配关系保留。',
      remarks: '2026 夏季保障结束。',
      isCurrentlyEffective: false,
      isGroupControlled: false,
      canMaintain: true,
      version: '5',
      createdAt: '2026-06-01 09:00:00',
      updatedAt: '2026-08-31 18:20:00',
    },
  ],
  catalog: {
    systems: [
      {
        id: 1,
        appCode: 'IAM',
        appName: '身份与权限中心',
        description: '统一身份、组织、角色和权限治理。',
        icon: 'mdi:shield-account-outline',
        routePrefix: '/iam',
        status: 'ACTIVE',
        remarks: '平台核心权限系统。',
        canMaintain: false,
        version: '21',
        createdAt: '2025-01-01 00:00:00',
        createdBy: 'system',
        updatedAt: '2026-09-06 18:12:02',
        updatedBy: 'platform-admin',
      },
      {
        id: 2,
        appCode: 'TMS',
        appName: '运输管理',
        description: '订单、调度、行程与线路运营。',
        icon: 'mdi:truck-fast-outline',
        routePrefix: '/tms',
        status: 'ACTIVE',
        remarks: '',
        canMaintain: true,
        version: '15',
        createdAt: '2025-02-08 10:00:00',
        createdBy: 'platform-admin',
        updatedAt: '2026-09-06 17:30:18',
        updatedBy: 'platform-admin',
      },
      {
        id: 3,
        appCode: 'VMS',
        appName: '车辆管理',
        description: '车辆、司机、证照和维保。',
        icon: 'mdi:car-cog',
        routePrefix: '/vms',
        status: 'DISABLED',
        remarks: '待车务模块重新启用。',
        canMaintain: true,
        version: '8',
        createdAt: '2025-03-12 10:00:00',
        createdBy: 'platform-admin',
        updatedAt: '2026-09-02 09:18:42',
        updatedBy: 'platform-admin',
      },
    ],
    resourcesBySystem: {
      1: [
        resource({
          id: 101,
          appId: 1,
          resourceCode: 'iam.management',
          resourceName: 'IAM 管理',
          resourceType: 'MODULE',
          canMaintain: false,
          children: [
            resource({
              id: 102,
              appId: 1,
              parentId: 101,
              resourceCode: 'iam.roles.page',
              resourceName: '角色管理',
              resourceType: 'MENU',
              routePath: '/iam/roles',
              component: 'RoleManagementPage',
              children: [
                resource({
                  id: 103,
                  appId: 1,
                  parentId: 102,
                  resourceCode: 'iam.roles.function-permissions',
                  resourceName: '角色功能权限',
                  resourceType: 'PAGE',
                  routePath: '/iam/roles/function-permissions',
                  component: 'RoleFunctionPermissionPage',
                  permissionCode: 'iam:roles:function-permissions',
                  children: [
                    resource({
                      id: 104,
                      appId: 1,
                      parentId: 103,
                      resourceCode: 'iam.roles.function-permissions.save',
                      resourceName: '保存功能权限',
                      resourceType: 'FUNCTION',
                      permissionCode: 'iam:roles:function-permissions:update',
                      httpMethod: 'POST',
                      apiPath: '/iam-admin/RolePermission/SaveFunctionPermissions',
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
      ],
      2: [
        resource({
          id: 201,
          appId: 2,
          resourceCode: 'tms.dispatch',
          resourceName: '运输调度',
          resourceType: 'MODULE',
          children: [
            resource({
              id: 202,
              appId: 2,
              parentId: 201,
              resourceCode: 'tms.orders.page',
              resourceName: '运输订单',
              resourceType: 'MENU',
              routePath: '/tms/orders',
              component: 'OrderListPage',
              permissionSource: 'direct',
              children: [
                resource({
                  id: 203,
                  appId: 2,
                  parentId: 202,
                  resourceCode: 'tms.orders.view',
                  resourceName: '查看订单、运输全程轨迹、签收凭证、费用明细与异常处置完整详情',
                  resourceType: 'FUNCTION',
                  permissionCode: 'tms.order.view',
                  permissionSource: 'none',
                }),
                resource({
                  id: 204,
                  appId: 2,
                  parentId: 202,
                  resourceCode: 'tms.orders.export',
                  resourceName: '导出订单',
                  resourceType: 'FUNCTION',
                  permissionCode: 'tms.order.export',
                  permissionSource: 'direct',
                }),
                resource({
                  id: 205,
                  appId: 2,
                  parentId: 202,
                  resourceCode: 'tms.orders.api',
                  resourceName: '订单查询接口',
                  resourceType: 'FUNCTION',
                  httpMethod: 'POST',
                  apiPath: '/tms-admin/Order/Query',
                  isVisible: false,
                  permissionSource: 'none',
                }),
              ],
            }),
          ],
        }),
      ],
      3: [
        resource({
          id: 301,
          appId: 3,
          resourceCode: 'vms.vehicle',
          resourceName: '车辆档案',
          resourceType: 'MODULE',
          status: 'ACTIVE',
          isCurrentlyEffective: false,
          invalidReason: '所属系统已停用',
          children: [
            resource({
              id: 302,
              appId: 3,
              parentId: 301,
              resourceCode: 'vms.vehicles.page',
              resourceName: '车辆列表',
              resourceType: 'MENU',
              routePath: '/vms/vehicles',
              isCurrentlyEffective: false,
              invalidReason: '所属系统已停用',
              children: [
                resource({
                  id: 303,
                  appId: 3,
                  parentId: 302,
                  resourceCode: 'vms.vehicle.legacy',
                  resourceName: '历史证照同步',
                  resourceType: 'FUNCTION',
                  isCurrentlyEffective: false,
                  invalidReason: '资源配置无效',
                }),
              ],
            }),
          ],
        }),
      ],
    },
    deleteImpacts: [
      {
        entityType: 'system',
        entityId: 2,
        descendantCount: 0,
        resourceCount: 5,
      },
      {
        entityType: 'resource',
        entityId: 201,
        descendantCount: 4,
        resourceCount: 5,
      },
      {
        entityType: 'resource',
        entityId: 202,
        descendantCount: 0,
        resourceCount: 1,
      },
    ],
  },
  dataDomains: [
    {
      id: 801,
      appId: 2,
      appCode: 'TMS',
      domainCode: 'shipment',
      domainName: '运输任务',
      supportedScopes: ['SELF', 'ORG', 'ORG_AND_CHILDREN', 'TENANT', 'GROUP', 'CUSTOM'],
      selfDefinition: '本人负责、调度或作为业务经办人的运输任务。',
      status: 'ACTIVE',
      linkedResourceIds: [203, 204, 205],
      isConfigurationValid: true,
      invalidReason: '',
    },
    {
      id: 802,
      appId: 3,
      appCode: 'VMS',
      domainCode: 'vehicle',
      domainName: '车辆档案',
      supportedScopes: ['ORG', 'ORG_AND_CHILDREN', 'TENANT'],
      selfDefinition: '本人作为当前责任人的车辆。',
      status: 'ACTIVE',
      linkedResourceIds: [302],
      isConfigurationValid: true,
      invalidReason: '',
    },
    {
      id: 803,
      appId: 2,
      appCode: 'TMS',
      domainCode: 'legacy_dispatch',
      domainName: '历史调度数据',
      supportedScopes: ['TENANT'],
      selfDefinition: '无 SELF 语义。',
      status: 'DISABLED',
      linkedResourceIds: [],
      isConfigurationValid: false,
      invalidReason: '域已停用且无有效资源绑定',
    },
  ],
  invalidDataPermissionResources: [
    {
      resourceId: 303,
      appId: 3,
      resourceCode: 'vms.vehicle.legacy',
      resourceName: '历史证照同步',
      invalidReason: '资源未关联有效的数据权限域',
    },
  ],
  roleDataPermissions: [
    {
      domainCode: 'shipment',
      domainName: '运输任务',
      isConfigured: true,
      scopeMode: 'ORG_AND_CHILDREN',
      targetTenantIds: [],
      targetTenantNames: [],
      isCurrentlyEffective: true,
      invalidReason: '',
      version: '7',
    },
    {
      domainCode: 'vehicle',
      domainName: '车辆档案',
      isConfigured: false,
      targetTenantIds: [],
      targetTenantNames: [],
      isCurrentlyEffective: false,
      invalidReason: '未配置：无数据访问权',
      version: '0',
    },
    {
      domainCode: 'audit',
      domainName: '运输审计',
      isConfigured: true,
      scopeMode: 'CUSTOM',
      targetTenantIds: [7, 9],
      targetTenantNames: ['陆链华东运营中心', '陆链华南运营中心'],
      isCurrentlyEffective: true,
      invalidReason: '',
      version: '4',
    },
  ],
  assignments: [
    {
      assignmentId: 9001,
      tenantId: 7,
      tenantUserId: 301,
      tenantUserCode: 'HD00017',
      displayName: '林嘉',
      roleId: 504,
      roleCode: 'tenant_admin',
      roleName: 'Tenant 管理员',
      roleType: 'SYSTEM',
      isTenantAdminIdentity: true,
      isGroupControlled: false,
      isAssigned: true,
      isCurrentlyEffective: true,
      canMaintain: true,
      invalidReason: '',
      memberVersion: '18',
    },
    {
      assignmentId: 9002,
      tenantId: 7,
      tenantUserId: 301,
      tenantUserCode: 'HD00017',
      displayName: '林嘉',
      roleId: 501,
      roleCode: 'dispatch_manager',
      roleName: '调度经理',
      roleType: 'CUSTOM',
      isTenantAdminIdentity: false,
      isGroupControlled: false,
      isAssigned: true,
      isCurrentlyEffective: true,
      canMaintain: true,
      invalidReason: '',
      memberVersion: '18',
    },
    {
      assignmentId: 9003,
      tenantId: 7,
      tenantUserId: 302,
      tenantUserCode: 'HD00028',
      displayName: '顾敏',
      roleId: 501,
      roleCode: 'dispatch_manager',
      roleName: '调度经理',
      roleType: 'CUSTOM',
      isTenantAdminIdentity: false,
      isGroupControlled: false,
      isAssigned: true,
      isCurrentlyEffective: true,
      canMaintain: true,
      invalidReason: '',
      memberVersion: '11',
    },
    {
      assignmentId: 9004,
      tenantId: 7,
      tenantUserId: 303,
      tenantUserCode: 'HD00041',
      displayName: '沈拓',
      roleId: 505,
      roleCode: 'temporary_dispatch',
      roleName: '临时调度员',
      roleType: 'CUSTOM',
      isTenantAdminIdentity: false,
      isGroupControlled: false,
      isAssigned: true,
      isCurrentlyEffective: false,
      canMaintain: true,
      invalidReason: '角色已停用',
      memberVersion: '7',
    },
    {
      assignmentId: 9005,
      tenantId: 7,
      tenantUserId: 304,
      tenantUserCode: 'HD00052',
      displayName: '罗青',
      roleId: 503,
      roleCode: 'group_auditor',
      roleName: '集团审计查看',
      roleType: 'CUSTOM',
      isTenantAdminIdentity: false,
      isGroupControlled: true,
      isAssigned: true,
      isCurrentlyEffective: false,
      canMaintain: false,
      invalidReason: '成员当前已失效',
      memberVersion: '13',
    },
  ],
  directResourceIds: [202, 204],
}

const userPermissionRoles: FunctionPermissionRole[] = [
  {
    id: 501,
    tenantId: 7,
    tenantCode: 'LL-HUADONG',
    roleCode: 'dispatch_manager',
    roleName: '调度经理',
    roleType: 'CUSTOM',
  },
]

function asUserPermissionTree(nodes: ResourceNode[]): ResourceNode[] {
  return nodes.map((node) => {
    const isEffectiveFunction = [104, 203, 204].includes(node.id)
    const sourceRoles = isEffectiveFunction
      ? node.id === 203
        ? userPermissionRoles
        : [userPermissionRoles[0]!]
      : []

    return {
      ...node,
      canMaintain: false,
      isDirect: false,
      isNavigationOnly: node.resourceType !== 'FUNCTION',
      permissionSource: node.resourceType !== 'FUNCTION' ? 'navigation' : 'none',
      ...(sourceRoles.length
        ? {
            sourceRoles,
            sourceRoleNames: sourceRoles.map((role) => role.roleName),
          }
        : { sourceRoles: [], sourceRoleNames: [] }),
      children: asUserPermissionTree(node.children ?? []),
    }
  })
}

const userPermissionSystems = accessControlFixture.catalog.systems.filter(
  (system) => system.status === 'ACTIVE',
)
const userPermissionResources = Object.fromEntries(
  userPermissionSystems.map((system) => [
    system.id,
    asUserPermissionTree(accessControlFixture.catalog.resourcesBySystem[system.id] ?? []),
  ]),
)

export const userFunctionPermissionFixture: UserFunctionPermissionFixture = {
  subject: {
    subjectType: 'member',
    subjectId: 301,
    tenantId: 7,
    subjectCode: 'HD00017',
    subjectName: '林嘉',
    isCurrentlyEffective: true,
    invalidReason: '',
    version: '63925010284517031',
  },
  roles: userPermissionRoles,
  systems: userPermissionSystems,
  resourcesBySystem: userPermissionResources,
  effectiveResourceIds: [104, 203, 204],
}
