import type {
  TrainingEmployeeArchiveDto,
  TrainingEmployeeTaskRecordDto,
  TrainingOverviewDto,
  TrainingPagedReportDto,
  TrainingReportScopeDto,
  TrainingTrendsDto,
} from '../types/trainingOperationsContracts'
import type { TrainingOperationsFixture } from '../types/trainingOperations'

const reportScope: TrainingReportScopeDto = {
  employee_exam_ids: [],
  time_zone: 'Asia/Shanghai',
  tenant_id: 1,
  as_of: '2026-09-17T10:00:00+08:00',
  employee_ids: [],
  drilldown_scope: 'INCOMPLETE',
  time_boundary: '2026-09-17T10:00:00+08:00',
  start_at_from: '2026-01-01T00:00:00+08:00',
  start_at_to: '2027-01-01T00:00:00+08:00',
}

export const trainingOverviewFixture = {
  scope: reportScope,
  warnings: [],
  task_count: 5,
  not_started_task_count: 2,
  active_task_count: 1,
  overdue_task_count: 1,
  completed_task_count: 1,
  distinct_course_count: 7,
  employees: {
    employee_task_count: 1_233,
    distinct_employee_count: 304,
    required_count: 1_224,
    completed_count: 582,
    incomplete_count: 642,
    current_overdue_count: 42,
    ever_overdue_count: 49,
    excluded_count: 9,
    effective_learning_seconds: 8_684_400,
    final_exam_count: 835,
    final_passed_count: 782,
    completion_rate: 47.5,
    final_pass_rate: 93.7,
    has_required_employees: true,
  },
} satisfies TrainingOverviewDto

export const trainingTrendsFixture = {
  scope: reportScope,
  warnings: [],
  granularity: 'MONTH',
  task_status_distribution: {
    NOT_STARTED: 2,
    ACTIVE: 1,
    OVERDUE: 1,
    COMPLETED: 1,
  },
  points: [
    {
      period_start: '2026-04-01',
      training_completed_count: 84,
      course_completed_count: 286,
      exam_submitted_count: 92,
      exam_passed_count: 81,
    },
    {
      period_start: '2026-05-01',
      training_completed_count: 96,
      course_completed_count: 348,
      exam_submitted_count: 108,
      exam_passed_count: 99,
    },
    {
      period_start: '2026-06-01',
      training_completed_count: 99,
      course_completed_count: 394,
      exam_submitted_count: 112,
      exam_passed_count: 105,
    },
    {
      period_start: '2026-07-01',
      training_completed_count: 62,
      course_completed_count: 243,
      exam_submitted_count: 76,
      exam_passed_count: 68,
    },
    {
      period_start: '2026-08-01',
      training_completed_count: 91,
      course_completed_count: 317,
      exam_submitted_count: 103,
      exam_passed_count: 95,
    },
    {
      period_start: '2026-09-01',
      training_completed_count: 150,
      course_completed_count: 461,
      exam_submitted_count: 166,
      exam_passed_count: 151,
    },
  ],
} satisfies TrainingTrendsDto

const incompleteItems: TrainingEmployeeTaskRecordDto[] = [
  {
    id: 301,
    training_id: 101,
    training_task_id: 201,
    employee_id: 9001,
    is_required: true,
    assigned_at: '2026-07-01T08:12:00+08:00',
    status: 'EXAM_FAILED',
    course_learning_status: 'COMPLETED',
    exam_status: 'FAILED',
    learned_course_count: 4,
    course_count: 4,
    ever_overdue: true,
    overdue_at: '2026-09-15T00:00:00+08:00',
    total_learning_seconds: 4_920,
    final_score: 78,
    final_passed: false,
    profile: {
      employee_id: 9001,
      is_available: true,
      user_name: 'SD-JS-00018',
      real_name: '陈海峰',
      display_name: '陈海峰',
      organization_names: '山东运输中心',
      position_names: '危化品驾驶员',
    },
    plan_year: 2026,
    plan_name: '2026 年度驾驶员安全培训计划',
    task_name: '2026 第三季度驾驶员安全培训',
    task_type: 'QUARTERLY',
    period_key: '2026 Q3',
    start_at: '2026-07-01T00:00:00+08:00',
    deadline_at: '2026-09-30T23:59:00+08:00',
    task_status: 'ACTIVE',
    first_learning_at: '2026-07-03T09:18:00+08:00',
  },
  {
    id: 303,
    training_id: 101,
    training_task_id: 201,
    employee_id: 9003,
    is_required: false,
    assigned_at: '2026-07-01T08:12:00+08:00',
    excluded_at: '2026-09-05T10:30:00+08:00',
    status: 'LEARNING',
    course_learning_status: 'LEARNING',
    exam_status: 'NOT_STARTED',
    learned_course_count: 1,
    course_count: 4,
    ever_overdue: false,
    total_learning_seconds: 2_460,
    profile: {
      employee_id: 9003,
      is_available: true,
      user_name: 'AH-JS-00043',
      real_name: '韩雪松',
      display_name: '韩雪松',
      organization_names: '皖北运输中心',
      position_names: '冷链驾驶员',
    },
    plan_year: 2026,
    plan_name: '2026 年度驾驶员安全培训计划',
    task_name: '2026 第三季度驾驶员安全培训',
    task_type: 'QUARTERLY',
    period_key: '2026 Q3',
    start_at: '2026-07-01T00:00:00+08:00',
    deadline_at: '2026-09-30T23:59:00+08:00',
    task_status: 'ACTIVE',
    first_learning_at: '2026-07-08T14:05:00+08:00',
  },
  {
    id: 304,
    training_id: 101,
    training_task_id: 201,
    employee_id: 9004,
    is_required: true,
    assigned_at: '2026-07-01T08:12:00+08:00',
    status: 'READY_FOR_EXAM',
    course_learning_status: 'COMPLETED',
    exam_status: 'IN_PROGRESS',
    learned_course_count: 4,
    course_count: 4,
    ever_overdue: false,
    total_learning_seconds: 9_120,
    profile: {
      employee_id: 9004,
      is_available: true,
      user_name: 'SD-JS-00052',
      real_name: '王锐',
      display_name: '王锐',
      organization_names: '山东运输中心',
      position_names: '长途驾驶员',
    },
    plan_year: 2026,
    plan_name: '2026 年度驾驶员安全培训计划',
    task_name: '2026 第三季度驾驶员安全培训',
    task_type: 'QUARTERLY',
    period_key: '2026 Q3',
    start_at: '2026-07-01T00:00:00+08:00',
    deadline_at: '2026-09-30T23:59:00+08:00',
    task_status: 'ACTIVE',
    first_learning_at: '2026-07-02T11:36:00+08:00',
  },
]

export const trainingIncompleteFixture = {
  scope: reportScope,
  warnings: [],
  total: incompleteItems.length,
  page_index: 1,
  page_size: 10,
  items: incompleteItems,
} satisfies TrainingPagedReportDto<TrainingEmployeeTaskRecordDto>

export const trainingOperationsFixture: TrainingOperationsFixture = {
  plans: [
    {
      id: 101,
      planType: 'ANNUAL',
      year: 2026,
      name: '2026 年度驾驶员安全培训计划',
      startAt: '2026-01-01',
      endAt: '2026-12-31',
      frequency: 'QUARTERLY',
      status: 'PUBLISHED',
      currentEmployees: 286,
      historicalEmployees: 304,
      taskCount: 4,
      notStartedTaskCount: 2,
      activeTaskCount: 1,
      overdueTaskCount: 0,
      completedTaskCount: 1,
      updatedAt: '2026-09-16 16:42',
    },
    {
      id: 104,
      planType: 'STANDING',
      name: '新员工与返岗安全常设培训',
      startAt: '2026-09-01',
      status: 'PUBLISHED',
      currentEmployees: 38,
      historicalEmployees: 42,
      taskCount: 1,
      notStartedTaskCount: 0,
      activeTaskCount: 1,
      overdueTaskCount: 0,
      completedTaskCount: 0,
      updatedAt: '2026-09-22 16:18',
    },
    {
      id: 102,
      planType: 'ANNUAL',
      year: 2026,
      name: '危险品运输专项提升计划',
      startAt: '2026-07-01',
      endAt: '2026-11-30',
      frequency: 'MONTHLY',
      status: 'PUBLISHED',
      currentEmployees: 96,
      historicalEmployees: 101,
      taskCount: 1,
      notStartedTaskCount: 0,
      activeTaskCount: 0,
      overdueTaskCount: 1,
      completedTaskCount: 0,
      updatedAt: '2026-09-15 09:20',
    },
    {
      id: 103,
      planType: 'ANNUAL',
      year: 2027,
      name: '2027 年度新员工培训计划',
      startAt: '2027-01-01',
      endAt: '2027-12-31',
      frequency: 'QUARTERLY',
      status: 'DRAFT',
      currentEmployees: 0,
      historicalEmployees: 0,
      taskCount: 0,
      notStartedTaskCount: 0,
      activeTaskCount: 0,
      overdueTaskCount: 0,
      completedTaskCount: 0,
      updatedAt: '2026-09-14 13:08',
    },
    {
      id: 105,
      planType: 'STANDING',
      name: '仓储新岗常设培训（草稿）',
      startAt: '2026-10-01',
      status: 'DRAFT',
      currentEmployees: 0,
      historicalEmployees: 0,
      taskCount: 0,
      notStartedTaskCount: 0,
      activeTaskCount: 0,
      overdueTaskCount: 0,
      completedTaskCount: 0,
      updatedAt: '2026-09-22 17:05',
    },
  ],
  planEmployees: [
    {
      id: 501,
      employeeId: 9001,
      employeeCode: 'SD-JS-00018',
      name: '陈海峰',
      organization: '山东运输中心',
      position: '危化品驾驶员',
      isCurrent: true,
      effectiveFrom: '2026-01-05',
    },
    {
      id: 502,
      employeeId: 9002,
      employeeCode: 'JS-ZB-00106',
      name: '周明宇',
      organization: '苏北运输中心',
      position: '长途驾驶员',
      isCurrent: true,
      effectiveFrom: '2026-01-08',
    },
    {
      id: 503,
      employeeId: 9003,
      employeeCode: 'AH-JS-00043',
      name: '韩雪松',
      organization: '皖北运输中心',
      position: '冷链驾驶员',
      isCurrent: false,
      effectiveFrom: '2026-02-02',
      effectiveTo: '2026-07-18',
    },
  ],
  tasks: [
    {
      id: 201,
      trainingId: 101,
      name: '2026 第三季度驾驶员安全培训',
      planName: '2026 年度驾驶员安全培训计划',
      period: '2026 Q3',
      taskType: 'QUARTERLY',
      startAt: '2026-07-01 00:00',
      endAt: '2026-09-30 23:59',
      status: 'ACTIVE',
      isLocked: true,
      expectedCount: 286,
      completedCount: 231,
      overdueCount: 18,
      excludedCount: 4,
      hasRequiredEmployees: true,
      courseCount: 4,
      examId: 701,
      examName: 'Q3 安全培训结业考试',
      updatedAt: '2026-09-16T08:42:00Z',
    },
    {
      id: 202,
      trainingId: 102,
      name: '危化品运输九月专项培训',
      planName: '危险品运输专项提升计划',
      period: '2026-09',
      taskType: 'MONTHLY',
      startAt: '2026-09-01 00:00',
      endAt: '2026-09-20 23:59',
      status: 'OVERDUE',
      isLocked: true,
      expectedCount: 96,
      completedCount: 72,
      overdueCount: 24,
      excludedCount: 2,
      hasRequiredEmployees: true,
      courseCount: 3,
      examId: 702,
      examName: '危化品运输专项考试',
      updatedAt: '2026-09-16T08:42:00Z',
    },
    {
      id: 203,
      trainingId: 101,
      name: '2026 第二季度驾驶员安全培训',
      planName: '2026 年度驾驶员安全培训计划',
      period: '2026 Q2',
      taskType: 'QUARTERLY',
      startAt: '2026-04-01 00:00',
      endAt: '2026-06-30 23:59',
      status: 'COMPLETED',
      isLocked: true,
      expectedCount: 279,
      completedCount: 279,
      overdueCount: 7,
      excludedCount: 3,
      hasRequiredEmployees: true,
      courseCount: 4,
      examId: 703,
      examName: 'Q2 安全培训结业考试',
      updatedAt: '2026-09-16T08:42:00Z',
    },
    {
      id: 204,
      trainingId: 101,
      name: '2026 第四季度驾驶员安全培训',
      planName: '2026 年度驾驶员安全培训计划',
      period: '2026 Q4',
      taskType: 'QUARTERLY',
      startAt: '2026-10-01 00:00',
      endAt: '2026-12-31 23:59',
      status: 'NOT_STARTED',
      isLocked: false,
      expectedCount: 286,
      completedCount: 0,
      overdueCount: 0,
      excludedCount: 0,
      hasRequiredEmployees: true,
      courseCount: 4,
      examId: 704,
      examName: 'Q4 安全培训结业考试',
      updatedAt: '2026-09-16T08:42:00Z',
    },
    {
      id: 205,
      trainingId: 101,
      name: '国庆节前安全临时培训',
      planName: '2026 年度驾驶员安全培训计划',
      period: 'TEMP-202609-01',
      taskType: 'TEMPORARY',
      startAt: '2026-09-24 08:00',
      endAt: '2026-09-28 18:00',
      status: 'NOT_STARTED',
      isLocked: false,
      expectedCount: 286,
      completedCount: 0,
      overdueCount: 0,
      excludedCount: 0,
      hasRequiredEmployees: true,
      courseCount: 2,
      examId: 705,
      examName: '节前安全快测',
      updatedAt: '2026-09-17T01:30:00Z',
    },
    {
      id: 206,
      trainingId: 104,
      name: '新员工与返岗安全培训',
      planName: '新员工与返岗安全常设培训',
      period: '长期开放',
      taskType: 'TEMPORARY',
      startAt: '2026-09-01 00:00',
      isLongRunning: true,
      contentVersion: 3,
      status: 'ACTIVE',
      isLocked: false,
      expectedCount: 44,
      completedCount: 38,
      overdueCount: 0,
      excludedCount: 0,
      hasRequiredEmployees: true,
      completionRate: 86.4,
      courseCount: 3,
      examId: 706,
      examName: '新员工安全准入考试',
      updatedAt: '2026-09-22T08:18:00Z',
    },
  ],
  taskCourses: [
    {
      taskCourseId: 601,
      courseId: 801,
      name: '安全法规基础',
      trainingType: '安全法规',
      status: 'ACTIVE',
      sortOrder: 1,
      notStartedCount: 25,
      learningCount: 30,
      completedCount: 231,
      requiredCount: 286,
      completionRate: 80.8,
    },
    {
      taskCourseId: 602,
      courseId: 802,
      name: '危化品应急处置',
      trainingType: '应急处置',
      status: 'ACTIVE',
      sortOrder: 2,
      notStartedCount: 43,
      learningCount: 56,
      completedCount: 187,
      requiredCount: 286,
      completionRate: 65.4,
    },
    {
      taskCourseId: 603,
      courseId: 803,
      name: '防御性驾驶',
      trainingType: '驾驶技能',
      status: 'ACTIVE',
      sortOrder: 3,
      notStartedCount: 51,
      learningCount: 64,
      completedCount: 171,
      requiredCount: 286,
      completionRate: 59.8,
    },
  ],
  taskExams: [
    {
      examId: 701,
      name: 'Q3 安全培训结业考试',
      status: 'ACTIVE',
      notStartedCount: 25,
      notExaminedCount: 33,
      inProgressCount: 8,
      submittedCount: 253,
      passedCount: 231,
      failedCount: 22,
      requiredCount: 286,
      examRate: 88.5,
      passRate: 91.3,
    },
  ],
  taskEmployees: [
    {
      id: 301,
      employeeId: 9001,
      employeeCode: 'SD-JS-00018',
      name: '陈海峰',
      organization: '山东运输中心',
      position: '危化品驾驶员',
      shouldTrain: true,
      status: 'EXAM_FAILED',
      courseLearningStatus: 'COMPLETED',
      examStatus: 'FAILED',
      learnedCourseCount: 4,
      courseCount: 4,
      assignedAt: '2026-07-01 08:12',
      executionNo: 1,
      assignmentType: 'PLAN',
      contentVersion: 1,
      learningMinutes: 82,
      wasOverdue: true,
      firstOverdueAt: '2026-09-15 00:00',
      finalScore: 78,
      finalPassed: false,
      canAdminComplete: true,
      canArrangeAgain: false,
      updatedAt: '2026-09-22T08:12:00Z',
    },
    {
      id: 302,
      employeeId: 9002,
      employeeCode: 'JS-ZB-00106',
      name: '周明宇',
      organization: '苏北运输中心',
      position: '长途驾驶员',
      shouldTrain: true,
      status: 'COMPLETED',
      courseLearningStatus: 'COMPLETED',
      examStatus: 'PASSED',
      learnedCourseCount: 4,
      courseCount: 4,
      assignedAt: '2026-07-01 08:12',
      executionNo: 1,
      assignmentType: 'PLAN',
      contentVersion: 1,
      learningMinutes: 164,
      wasOverdue: false,
      finalScore: 92,
      finalPassed: true,
      completedAt: '2026-08-22 17:46',
      completionSource: 'NORMAL',
      canAdminComplete: false,
      canArrangeAgain: true,
      updatedAt: '2026-08-22T09:46:00Z',
    },
    {
      id: 303,
      employeeId: 9003,
      employeeCode: 'AH-JS-00043',
      name: '韩雪松',
      organization: '皖北运输中心',
      position: '冷链驾驶员',
      shouldTrain: false,
      status: 'LEARNING',
      courseLearningStatus: 'LEARNING',
      examStatus: 'NOT_STARTED',
      learnedCourseCount: 1,
      courseCount: 4,
      assignedAt: '2026-07-01 08:12',
      executionNo: 1,
      assignmentType: 'PLAN',
      contentVersion: 1,
      excludedAt: '2026-09-05 10:30',
      learningMinutes: 41,
      wasOverdue: false,
      canAdminComplete: false,
      canArrangeAgain: true,
      updatedAt: '2026-09-05T02:30:00Z',
    },
    {
      id: 304,
      employeeId: 9004,
      employeeCode: 'SD-JS-00052',
      name: '王锐',
      organization: '山东运输中心',
      position: '长途驾驶员',
      shouldTrain: true,
      status: 'READY_FOR_EXAM',
      courseLearningStatus: 'COMPLETED',
      examStatus: 'IN_PROGRESS',
      learnedCourseCount: 4,
      courseCount: 4,
      assignedAt: '2026-07-01 08:12',
      executionNo: 1,
      assignmentType: 'PLAN',
      contentVersion: 1,
      learningMinutes: 152,
      wasOverdue: false,
      canAdminComplete: true,
      canArrangeAgain: false,
      updatedAt: '2026-09-22T08:14:00Z',
    },
    {
      id: 305,
      employeeId: 9005,
      employeeCode: 'SD-XR-00008',
      name: '李春明',
      organization: '山东运输中心',
      position: '配送驾驶员',
      shouldTrain: true,
      status: 'COMPLETED',
      courseLearningStatus: 'COMPLETED',
      examStatus: 'PASSED',
      learnedCourseCount: 3,
      courseCount: 3,
      assignedAt: '2026-09-03 09:20',
      executionNo: 1,
      assignmentType: 'ONBOARDING',
      contentVersion: 2,
      learningMinutes: 116,
      wasOverdue: false,
      finalScore: 88,
      finalPassed: true,
      completedAt: '2026-09-06 16:32',
      completionSource: 'NORMAL',
      canAdminComplete: false,
      canArrangeAgain: true,
      updatedAt: '2026-09-06T08:32:00Z',
    },
    {
      id: 306,
      employeeId: 9005,
      employeeCode: 'SD-XR-00008',
      name: '李春明',
      organization: '山东运输中心',
      position: '配送驾驶员',
      shouldTrain: true,
      status: 'COMPLETED',
      courseLearningStatus: 'NOT_STARTED',
      examStatus: 'NOT_STARTED',
      learnedCourseCount: 0,
      courseCount: 3,
      assignedAt: '2026-09-18 10:08',
      executionNo: 2,
      assignmentType: 'RETURN_TO_WORK',
      contentVersion: 3,
      learningMinutes: 0,
      wasOverdue: false,
      completedAt: '2026-09-20 14:30',
      completionSource: 'ADMIN',
      adminCompletedBy: '赵安全',
      adminCompletedAt: '2026-09-20 14:30',
      adminCompletionReason: '线下完成复岗安全核验，纸质材料已归档',
      canAdminComplete: false,
      canArrangeAgain: true,
      updatedAt: '2026-09-20T06:30:00Z',
    },
    {
      id: 307,
      employeeId: 9008,
      employeeCode: 'SD-XR-00011',
      name: '钱晓宇',
      organization: '山东运输中心',
      position: '配送驾驶员',
      shouldTrain: true,
      status: 'LEARNING',
      courseLearningStatus: 'LEARNING',
      examStatus: 'NOT_STARTED',
      learnedCourseCount: 1,
      courseCount: 3,
      assignedAt: '2026-09-22 10:20',
      executionNo: 1,
      assignmentType: 'ONBOARDING',
      contentVersion: 3,
      learningMinutes: 24,
      wasOverdue: false,
      canAdminComplete: true,
      canArrangeAgain: false,
      updatedAt: '2026-09-22T02:20:00Z',
    },
  ],
  archives: [
    {
      id: 401,
      employeeCode: 'SD-JS-00018',
      name: '陈海峰',
      organization: '山东运输中心',
      position: '危化品驾驶员',
      taskCount: 8,
      completedCount: 6,
      overdueCount: 2,
      finalPassedCount: 5,
      learningMinutes: 1032,
      latestTrainingAt: '2026-09-15 18:20',
    },
    {
      id: 402,
      employeeCode: 'JS-ZB-00106',
      name: '周明宇',
      organization: '苏北运输中心',
      position: '长途驾驶员',
      taskCount: 8,
      completedCount: 8,
      overdueCount: 0,
      finalPassedCount: 8,
      learningMinutes: 1264,
      latestTrainingAt: '2026-09-16 16:08',
    },
    {
      id: 403,
      employeeCode: 'AH-JS-00043',
      name: '韩雪松',
      organization: '皖北运输中心',
      position: '冷链驾驶员',
      taskCount: 7,
      completedCount: 6,
      overdueCount: 1,
      finalPassedCount: 6,
      learningMinutes: 946,
      latestTrainingAt: '2026-09-10 11:08',
    },
    {
      id: 404,
      employeeCode: 'SD-XR-00008',
      name: '李春明',
      organization: '山东运输中心',
      position: '配送驾驶员',
      taskCount: 2,
      completedCount: 2,
      overdueCount: 0,
      finalPassedCount: 1,
      learningMinutes: 116,
      latestTrainingAt: '2026-09-20 14:30',
    },
  ],
  autoEnrollmentRule: {
    id: 1001,
    trainingId: 104,
    trainingTaskId: 206,
    planName: '新员工与返岗安全常设培训',
    taskName: '新员工与返岗安全培训',
    isEnabled: true,
    enabledAt: '2026-09-02 09:00',
    updatedAt: '2026-09-22T08:18:00Z',
  },
  autoEnrollmentJobs: [
    {
      id: 1101,
      employeeId: 9005,
      employeeName: '李春明',
      memberEffectiveAt: '2026-09-03 09:18',
      status: 'SUCCEEDED',
      attemptCount: 1,
      trainingTaskEmployeeId: 305,
      updatedAt: '2026-09-03 09:20',
    },
    {
      id: 1102,
      employeeId: 9008,
      employeeName: '钱晓宇',
      memberEffectiveAt: '2026-09-22 10:00',
      status: 'FAILED',
      attemptCount: 2,
      nextRetryAt: '2026-09-22 10:30',
      lastError: '员工档案尚未同步完成',
      updatedAt: '2026-09-22 10:15',
    },
  ],
}

const archivePlanCounts = new Map<number, number>([
  [401, 2],
  [402, 2],
  [403, 1],
  [404, 1],
])

export const trainingArchiveReportFixture = {
  scope: reportScope,
  warnings: [],
  total: trainingOperationsFixture.archives.length,
  page_index: 1,
  page_size: 10,
  items: trainingOperationsFixture.archives.map(
    (item) =>
      ({
        employee_id: item.id,
        plan_count: archivePlanCounts.get(item.id) ?? 1,
        employee_task_count: item.taskCount,
        distinct_employee_count: 1,
        required_count: item.taskCount,
        completed_count: item.completedCount,
        incomplete_count: Math.max(0, item.taskCount - item.completedCount),
        current_overdue_count: item.overdueCount,
        ever_overdue_count: item.overdueCount,
        excluded_count: 0,
        effective_learning_seconds: item.learningMinutes * 60,
        final_exam_count: item.completedCount,
        final_passed_count: item.finalPassedCount,
        completion_rate: item.taskCount ? (item.completedCount / item.taskCount) * 100 : 100,
        final_pass_rate: item.completedCount
          ? (item.finalPassedCount / item.completedCount) * 100
          : 100,
        has_required_employees: item.taskCount > 0,
        latest_training_at: item.latestTrainingAt,
        profile: {
          employee_id: item.id,
          is_available: true,
          user_name: item.employeeCode,
          real_name: item.name,
          display_name: item.name,
          organization_names: item.organization,
          position_names: item.position,
        },
      }) satisfies TrainingEmployeeArchiveDto,
  ),
} satisfies TrainingPagedReportDto<TrainingEmployeeArchiveDto>
