import type { Component } from 'vue'

import approvedPrototypeManifest from '../approved-prototypes.json'

export const prototypeStatuses = [
  'draft',
  'reviewing',
  'approved',
  'implemented',
  'archived',
] as const

export type PrototypeStatus = (typeof prototypeStatuses)[number]
export type PreviewSource = 'legacy-prototype' | 'canonical-feature'

export interface UiPrototypeMetadata {
  id: string
  name: string
  subsystem: string
  feature: string
  pageType: string
  status: PrototypeStatus
  viewport: string
  pageSpec: string
  updatedAt: string
  source: PreviewSource
  productionRoute?: string
  pattern?: string
}

export interface UiPrototypeDefinition extends UiPrototypeMetadata {
  load: () => Promise<{ default: Component }>
}

const viewportLabel = approvedPrototypeManifest.viewports
  .map((viewport) => viewport.label)
  .join(' / ')

const approvedPrototypeLoaders: Record<string, UiPrototypeDefinition['load']> = {
  'platform-dashboard': () => import('./prototypes/platform/dashboard/PrototypePage.vue'),
}

const approvedPrototypes: UiPrototypeDefinition[] = approvedPrototypeManifest.prototypes.map(
  (prototype) => {
    const load = approvedPrototypeLoaders[prototype.id]

    if (!load) {
      throw new Error(`原型 ${prototype.id} 缺少组件加载器`)
    }

    return {
      id: prototype.id,
      name: prototype.name,
      subsystem: prototype.subsystem,
      feature: prototype.feature,
      pageType: prototype.pageType,
      status: prototype.status as PrototypeStatus,
      viewport: viewportLabel,
      pageSpec: prototype.pageSpec,
      updatedAt: prototype.updatedAt,
      source: 'legacy-prototype',
      productionRoute: prototype.productionRoute,
      pattern: prototype.pattern,
      load,
    }
  },
)

// 原型通过显式注册进入目录，避免扫描文件名形成不可控的隐式约定。
export const uiPrototypes: readonly UiPrototypeDefinition[] = [
  ...approvedPrototypes,
  {
    id: 'vms-vehicle-list',
    name: '车辆档案（历史样本）',
    subsystem: 'vms',
    feature: 'vehicles',
    pageType: 'ListPage',
    status: 'archived',
    viewport: viewportLabel,
    pageSpec: '已退役：原生产样本不再注册路由',
    updatedAt: '2026-09-20',
    source: 'legacy-prototype',
    pattern: 'ListPageTemplate',
    load: () => import('./prototypes/vms/vehicles/PrototypePage.vue'),
  },
  {
    id: 'platform-framework-shell',
    name: '物流平台统一框架页',
    subsystem: 'platform',
    feature: 'framework',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/platform-framework-shell.yaml',
    updatedAt: '2026-09-04',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/platform/framework/public.preview'),
  },
  {
    id: 'iam-login',
    name: '统一登录页',
    subsystem: 'iam',
    feature: 'login',
    pageType: 'AuthPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-login.yaml',
    updatedAt: '2026-09-04',
    source: 'canonical-feature',
    pattern: 'AuthPageTemplate',
    load: () => import('@feature-preview/iam/login/public.preview'),
  },
  {
    id: 'iam-password-recovery',
    name: '忘记密码页',
    subsystem: 'iam',
    feature: 'password-recovery',
    pageType: 'AuthPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-password-recovery.yaml',
    updatedAt: '2026-09-04',
    source: 'canonical-feature',
    pattern: 'AuthPageTemplate',
    load: () => import('@feature-preview/iam/password-recovery/public.preview'),
  },
  {
    id: 'iam-group-profile',
    name: '集团信息',
    subsystem: 'iam',
    feature: 'foundation',
    pageType: 'DetailPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-group-profile.yaml',
    updatedAt: '2026-09-06',
    source: 'canonical-feature',
    pattern: 'DetailPageTemplate',
    load: () => import('@feature-preview/iam/foundation/public.preview'),
  },
  {
    id: 'iam-tenant-management',
    name: 'Tenant 管理',
    subsystem: 'iam',
    feature: 'foundation',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-tenant-management.yaml',
    updatedAt: '2026-09-06',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/iam/foundation/public.preview'),
  },
  {
    id: 'iam-organization-management',
    name: '组织管理',
    subsystem: 'iam',
    feature: 'foundation',
    pageType: 'WorkspacePage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-organization-management.yaml',
    updatedAt: '2026-09-06',
    source: 'canonical-feature',
    pattern: 'WorkspacePageTemplate',
    load: () => import('@feature-preview/iam/foundation/public.preview'),
  },
  {
    id: 'iam-position-management',
    name: '岗位管理',
    subsystem: 'iam',
    feature: 'foundation',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-position-management.yaml',
    updatedAt: '2026-09-06',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/iam/foundation/public.preview'),
  },
  {
    id: 'iam-membership-management',
    name: '用户与 Tenant 成员',
    subsystem: 'iam',
    feature: 'foundation',
    pageType: 'ListPage',
    status: 'reviewing',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-membership-management.yaml',
    updatedAt: '2026-09-20',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/iam/foundation/public.preview'),
  },
  {
    id: 'iam-tenant-context',
    name: 'Tenant 选择与切换',
    subsystem: 'iam',
    feature: 'foundation',
    pageType: 'AuthPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-tenant-context.yaml',
    updatedAt: '2026-09-06',
    source: 'canonical-feature',
    pattern: 'AuthPageTemplate',
    load: () => import('@feature-preview/iam/foundation/public.preview'),
  },
  {
    id: 'iam-application-resources',
    name: '应用与权限资源',
    subsystem: 'iam',
    feature: 'application-resources',
    pageType: 'WorkspacePage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-application-resources.yaml',
    updatedAt: '2026-09-08',
    source: 'canonical-feature',
    pattern: 'WorkspacePageTemplate',
    load: () => import('@feature-preview/iam/application-resources/public.preview'),
  },
  {
    id: 'iam-role-management',
    name: '角色管理',
    subsystem: 'iam',
    feature: 'access-control',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-role-management.yaml',
    updatedAt: '2026-09-07',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/iam/access-control/public.preview'),
  },
  {
    id: 'iam-role-function-permissions',
    name: '角色功能权限',
    subsystem: 'iam',
    feature: 'access-control',
    pageType: 'WorkspacePage',
    status: 'reviewing',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-role-function-permissions.yaml',
    updatedAt: '2026-09-20',
    source: 'canonical-feature',
    pattern: 'WorkspacePageTemplate',
    load: () => import('@feature-preview/iam/access-control/public.preview'),
  },
  {
    id: 'iam-user-function-permissions',
    name: '用户角色与权限',
    subsystem: 'iam',
    feature: 'access-control',
    pageType: 'DetailPage',
    status: 'reviewing',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-user-function-permissions.yaml',
    updatedAt: '2026-09-20',
    source: 'canonical-feature',
    pattern: 'DetailPageTemplate',
    load: () => import('@feature-preview/iam/access-control/public.preview'),
  },
  {
    id: 'iam-role-data-permissions',
    name: '角色数据权限',
    subsystem: 'iam',
    feature: 'access-control',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-role-data-permissions.yaml',
    updatedAt: '2026-09-07',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/iam/access-control/public.preview'),
  },
  {
    id: 'iam-role-assignments',
    name: '角色成员',
    subsystem: 'iam',
    feature: 'access-control',
    pageType: 'ListPage',
    status: 'reviewing',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/iam-role-assignments.yaml',
    updatedAt: '2026-09-20',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/iam/access-control/public.preview'),
  },
  {
    id: 'training-course-management',
    name: '课程管理',
    subsystem: 'training',
    feature: 'content-exam',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-course-management.yaml',
    updatedAt: '2026-09-15',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/training/content-exam/public.preview'),
  },
  {
    id: 'training-question-bank',
    name: '题库管理',
    subsystem: 'training',
    feature: 'content-exam',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-question-bank.yaml',
    updatedAt: '2026-09-15',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/training/content-exam/public.preview'),
  },
  {
    id: 'training-paper-management',
    name: '试卷管理',
    subsystem: 'training',
    feature: 'content-exam',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-paper-management.yaml',
    updatedAt: '2026-09-15',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/training/content-exam/public.preview'),
  },
  {
    id: 'training-exam-configuration',
    name: '考试配置管理',
    subsystem: 'training',
    feature: 'content-exam',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-exam-configuration.yaml',
    updatedAt: '2026-09-15',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/training/content-exam/public.preview'),
  },
  {
    id: 'training-operations-overview',
    name: '培训概览',
    subsystem: 'training',
    feature: 'operations-archive',
    pageType: 'DashboardPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-operations-overview.yaml',
    productionRoute: '/iam/training/overview',
    updatedAt: '2026-09-17',
    source: 'canonical-feature',
    pattern: 'DashboardPageTemplate',
    load: () => import('@feature-preview/training/operations-archive/public.preview'),
  },
  {
    id: 'training-plan-management',
    name: '培训计划',
    subsystem: 'training',
    feature: 'operations-archive',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-plan-management.yaml',
    productionRoute: '/iam/training/plans',
    updatedAt: '2026-09-17',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/training/operations-archive/public.preview'),
  },
  {
    id: 'training-task-management',
    name: '培训任务（已由计划详情替代）',
    subsystem: 'training',
    feature: 'operations-archive',
    pageType: 'ListPage',
    status: 'archived',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-task-management.yaml',
    updatedAt: '2026-09-17',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/training/operations-archive/public.preview'),
  },
  {
    id: 'training-plan-detail',
    name: '培训计划详情',
    subsystem: 'training',
    feature: 'operations-archive',
    pageType: 'DetailPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-plan-detail.yaml',
    productionRoute: '/iam/training/plans/:planId',
    updatedAt: '2026-09-17',
    source: 'canonical-feature',
    pattern: 'DetailPageTemplate',
    load: () => import('@feature-preview/training/operations-archive/public.preview'),
  },
  {
    id: 'training-task-detail',
    name: '培训任务详情',
    subsystem: 'training',
    feature: 'operations-archive',
    pageType: 'DetailPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-task-detail.yaml',
    productionRoute: '/iam/training/plans/:planId/tasks/:taskId',
    updatedAt: '2026-09-17',
    source: 'canonical-feature',
    pattern: 'DetailPageTemplate',
    load: () => import('@feature-preview/training/operations-archive/public.preview'),
  },
  {
    id: 'training-employee-archives',
    name: '员工培训档案',
    subsystem: 'training',
    feature: 'operations-archive',
    pageType: 'ListPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-employee-archives.yaml',
    productionRoute: '/iam/training/employee-archives',
    updatedAt: '2026-09-17',
    source: 'canonical-feature',
    pattern: 'ListPageTemplate',
    load: () => import('@feature-preview/training/operations-archive/public.preview'),
  },
  {
    id: 'training-special-statistics',
    name: '专项统计',
    subsystem: 'training',
    feature: 'operations-archive',
    pageType: 'DashboardPage',
    status: 'approved',
    viewport: viewportLabel,
    pageSpec: 'docs/page-specs/training-special-statistics.yaml',
    productionRoute: '/iam/training/statistics',
    updatedAt: '2026-09-17',
    source: 'canonical-feature',
    pattern: 'DashboardPageTemplate',
    load: () => import('@feature-preview/training/operations-archive/public.preview'),
  },
  {
    id: 'shared.template.page',
    name: '页面原型模板',
    subsystem: 'shared',
    feature: 'template',
    pageType: 'WorkspacePage',
    status: 'draft',
    viewport: viewportLabel,
    pageSpec: '待关联',
    updatedAt: '2026-09-02',
    source: 'legacy-prototype',
    load: () => import('./prototypes/_template/PrototypePage.vue'),
  },
]
