import type {
  GroupProfile,
  MembershipRecord,
  OrganizationNode,
  PositionRecord,
  TenantOption,
  TenantRecord,
} from '../types/foundation'
import groupLogoUrl from '../assets/group-logo.svg'

export const foundationFixture: {
  group: GroupProfile
  tenants: TenantRecord[]
  organizations: OrganizationNode[]
  positions: PositionRecord[]
  memberships: MembershipRecord[]
  tenantOptions: TenantOption[]
} = {
  group: {
    id: 1,
    groupCode: 'SS-EXPRESS',
    groupName: '陆链物流集团',
    fullName: '山东陆链智慧物流集团有限公司',
    shortName: '陆链物流',
    logoUrl: groupLogoUrl,
    platformName: 'SS Express 物流协同平台',
    description: '面向多组织、多租户的运输与车辆协同管理平台。',
    contactName: '周宁',
    contactPhone: '0531-8890 6608',
    contactEmail: 'platform@ss-express.cn',
    website: 'www.ss-express.cn',
    address: '山东省济南市高新区舜华路 2000 号',
    timezone: 'Asia/Shanghai (UTC+08:00)',
    language: '简体中文',
    remarks: '集团统一品牌资料由平台管理员维护。',
    version: '12',
    updatedAt: '2026-09-05 16:42:18',
  },
  tenants: [
    {
      id: 3,
      groupId: 1,
      code: 'HMXTSD',
      name: '汉明巡天山东',
      type: '企业租户',
      companyName: '汉明巡天（山东）供应链有限公司',
      address: '山东省济南市历城区港兴一路 88 号',
      status: 'ACTIVE',
      contactName: '王海峰',
      contactPhone: '186 5310 8826',
      contactEmail: 'wanghaifeng@hmxtsd.cn',
      domain: 'hmxtsd.ss-express.cn',
      subdomain: 'hmxtsd',
      logoUrl: '',
      timezone: 'Asia/Shanghai',
      language: 'zh-CN',
      sortOrder: 10,
      version: '8',
      remarks: '山东区域核心企业 Tenant。',
      createdAt: '2025-01-08 09:16:42',
      memberCount: 128,
      updatedAt: '2026-09-05 15:28:36',
      createdBy: 'platform.admin',
      updatedBy: 'hmxt.admin',
    },
    {
      id: 7,
      groupId: 1,
      code: 'LL-HUADONG',
      name: '陆链华东运营中心',
      type: '区域中心',
      companyName: '陆链华东物流科技有限公司',
      address: '上海市嘉定区汇源路 55 号',
      status: 'ACTIVE',
      contactName: '林嘉',
      contactPhone: '138 1682 4431',
      contactEmail: 'linjia@ll-east.cn',
      domain: 'east.ss-express.cn',
      subdomain: 'east',
      logoUrl: '',
      timezone: 'Asia/Shanghai',
      language: 'zh-CN',
      sortOrder: 20,
      version: '16',
      remarks: '负责华东区域运输运营。',
      createdAt: '2025-02-12 10:06:18',
      memberCount: 86,
      updatedAt: '2026-09-04 11:09:24',
      createdBy: 'platform.admin',
      updatedBy: 'linjia',
    },
    {
      id: 9,
      groupId: 1,
      code: 'LL-HUANAN',
      name: '陆链华南运营中心',
      type: '区域中心',
      companyName: '陆链华南物流服务有限公司',
      address: '广东省广州市白云区空港大道 120 号',
      status: 'ACTIVE',
      contactName: '陈澄',
      contactPhone: '139 2228 7810',
      contactEmail: 'chencheng@ll-south.cn',
      domain: 'south.ss-express.cn',
      subdomain: 'south',
      logoUrl: '',
      timezone: 'Asia/Shanghai',
      language: 'zh-CN',
      sortOrder: 30,
      version: '9',
      remarks: '负责华南区域运输运营。',
      createdAt: '2025-03-18 14:22:09',
      memberCount: 64,
      updatedAt: '2026-09-03 09:38:11',
      createdBy: 'platform.admin',
      updatedBy: 'chencheng',
    },
    {
      id: 12,
      groupId: 1,
      code: 'LL-NORTH',
      name: '陆链北方试运营中心',
      type: '区域中心',
      companyName: '陆链北方运输有限公司',
      address: '北京市顺义区物流园八街 19 号',
      status: 'DISABLED',
      contactName: '赵琪',
      contactPhone: '136 0108 9021',
      contactEmail: 'zhaoqi@ll-north.cn',
      domain: 'north.ss-express.cn',
      subdomain: 'north',
      logoUrl: '',
      timezone: 'Asia/Shanghai',
      language: 'zh-CN',
      sortOrder: 90,
      version: '5',
      remarks: '试运营结束，保留历史数据。',
      createdAt: '2026-03-01 08:30:00',
      memberCount: 19,
      updatedAt: '2026-08-26 17:05:02',
      createdBy: 'platform.admin',
      updatedBy: 'platform.admin',
    },
  ],
  organizations: [
    {
      id: 101,
      code: 'HD-OPS',
      name: '华东运营中心',
      type: '运营中心',
      leader: '林嘉',
      status: 'ACTIVE',
      activeMemberCount: 86,
      children: [
        {
          id: 102,
          parentId: 101,
          code: 'HD-DISPATCH',
          name: '调度管理部',
          type: '职能部门',
          leader: '顾敏',
          status: 'ACTIVE',
          activeMemberCount: 24,
          children: [
            {
              id: 104,
              parentId: 102,
              code: 'HD-LINEHAUL',
              name: '干线调度组',
              type: '业务小组',
              leader: '沈拓',
              status: 'ACTIVE',
              activeMemberCount: 11,
            },
          ],
        },
        {
          id: 103,
          parentId: 101,
          code: 'HD-FLEET',
          name: '车辆运营部',
          type: '职能部门',
          leader: '罗青',
          status: 'ACTIVE',
          activeMemberCount: 31,
        },
        {
          id: 105,
          parentId: 101,
          code: 'HD-CS',
          name: '客户服务部',
          type: '职能部门',
          leader: '未设置',
          status: 'DISABLED',
          activeMemberCount: 0,
        },
      ],
    },
  ],
  positions: [
    {
      id: 201,
      code: 'DISPATCH-MGR',
      name: '调度经理',
      type: '管理岗位',
      status: 'ACTIVE',
      activeMemberCount: 4,
      sortOrder: 10,
      updatedAt: '2026-09-05 14:16:20',
    },
    {
      id: 202,
      code: 'LINEHAUL-DISPATCH',
      name: '干线调度员',
      type: '业务岗位',
      status: 'ACTIVE',
      activeMemberCount: 11,
      sortOrder: 20,
      updatedAt: '2026-09-05 10:42:06',
    },
    {
      id: 203,
      code: 'FLEET-SPECIALIST',
      name: '车队运营专员',
      type: '业务岗位',
      status: 'ACTIVE',
      activeMemberCount: 18,
      sortOrder: 30,
      updatedAt: '2026-09-03 09:20:41',
    },
    {
      id: 204,
      code: 'TEMP-CS',
      name: '临时客服岗',
      type: '临时岗位',
      status: 'DISABLED',
      activeMemberCount: 0,
      sortOrder: 90,
      updatedAt: '2026-08-28 16:05:39',
    },
  ],
  memberships: [
    {
      id: 301,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      tenantName: '陆链华东运营中心',
      tenantTimezone: 'Asia/Shanghai',
      userId: 501,
      memberCode: 'HD00017',
      displayName: '林嘉',
      memberUserType: '正式员工',
      userName: 'linjia',
      realName: '林嘉',
      nickName: '嘉姐',
      phone: '138 1682 4431',
      email: 'linjia@ll-east.cn',
      avatarUrl: '',
      globalUserType: '平台用户',
      userStatus: 'ACTIVE',
      memberStatus: 'ACTIVE',
      effectiveness: 'EFFECTIVE',
      isTenantAdmin: true,
      isDefaultTenant: true,
      joinedAt: '2025-01-01 09:00:00',
      leftAt: '',
      primaryOrganization: '华东运营中心',
      primaryPosition: '运营负责人',
      effectiveStart: '2025-01-01 00:00:00',
      effectiveEnd: '',
      effectiveRange: '2025-01-01 ～ 长期有效',
      remarks: '华东运营中心初始 Tenant 管理员。',
      userRemarks: '集团运营管理人员。',
      version: '18',
      userVersion: '9',
      updatedAt: '2026-09-05 16:10:20',
      userUpdatedAt: '2026-09-05 15:42:11',
      organizations: [
        {
          id: 701,
          targetId: 101,
          code: 'HD-OPS',
          name: '华东运营中心',
          isPrimary: true,
          effectiveStart: '2025-01-01 00:00:00',
          effectiveEnd: '',
          isCurrentlyEffective: true,
          status: 'ACTIVE',
          remarks: '主要组织',
          version: '4',
          updatedAt: '2026-06-10 09:15:20',
        },
        {
          id: 702,
          targetId: 106,
          code: 'HD-SUPPORT',
          name: '运输支持组',
          isPrimary: false,
          effectiveStart: '2024-03-01 00:00:00',
          effectiveEnd: '2024-12-31 23:59:59',
          isCurrentlyEffective: false,
          status: 'DISABLED',
          remarks: '历史辅助组织',
          version: '2',
          updatedAt: '2025-01-01 08:12:09',
        },
      ],
      positions: [
        {
          id: 801,
          targetId: 205,
          code: 'OPS-LEAD',
          name: '运营负责人',
          isPrimary: true,
          effectiveStart: '2025-01-01 00:00:00',
          effectiveEnd: '',
          isCurrentlyEffective: true,
          status: 'ACTIVE',
          remarks: '主要岗位',
          version: '3',
          updatedAt: '2026-06-10 09:16:02',
        },
      ],
      tenantMemberships: [
        {
          id: 301,
          tenantId: 7,
          tenantCode: 'LL-HUADONG',
          tenantName: '陆链华东运营中心',
          memberCode: 'HD00017',
          displayName: '林嘉',
          status: 'ACTIVE',
          isTenantAdmin: true,
          isCurrentlyEffective: true,
          membershipIsCurrentlyEffective: true,
          memberVersion: '5',
          joinedAt: '2025-01-01 00:00:00',
          leftAt: '',
          tenantStatus: 'ACTIVE',
          tenantIsDeleted: false,
          effectiveRange: '2025-01-01 ～ 长期有效',
          timezone: 'Asia/Shanghai',
        },
        {
          id: 351,
          tenantId: 3,
          tenantCode: 'HMXTSD',
          tenantName: '汉明巡天山东',
          memberCode: 'SD00009',
          displayName: '林嘉',
          status: 'DISABLED',
          isTenantAdmin: false,
          isCurrentlyEffective: false,
          membershipIsCurrentlyEffective: false,
          memberVersion: '3',
          joinedAt: '2026-01-01 00:00:00',
          leftAt: '2026-08-31 23:59:59',
          tenantStatus: 'ACTIVE',
          tenantIsDeleted: false,
          effectiveRange: '2026-01-01 ～ 2026-08-31',
          timezone: 'Asia/Shanghai',
        },
      ],
    },
    {
      id: 302,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      tenantName: '陆链华东运营中心',
      tenantTimezone: 'Asia/Shanghai',
      userId: 502,
      memberCode: 'HD00126',
      displayName: '顾敏',
      memberUserType: '正式员工',
      userName: 'gumin',
      realName: '顾敏',
      nickName: '顾工',
      phone: '139 1802 7712',
      email: 'gumin@ll-east.cn',
      avatarUrl: '',
      globalUserType: '平台用户',
      userStatus: 'ACTIVE',
      memberStatus: 'ACTIVE',
      effectiveness: 'EFFECTIVE',
      isTenantAdmin: false,
      isDefaultTenant: true,
      joinedAt: '2025-05-16 09:00:00',
      leftAt: '',
      primaryOrganization: '调度管理部',
      primaryPosition: '调度经理',
      effectiveStart: '2025-05-16 00:00:00',
      effectiveEnd: '',
      effectiveRange: '2025-05-16 ～ 长期有效',
      remarks: '负责日常调度管理。',
      userRemarks: '华东调度业务负责人。',
      version: '12',
      userVersion: '6',
      updatedAt: '2026-09-04 11:09:24',
      userUpdatedAt: '2026-08-20 10:20:16',
      organizations: [
        {
          id: 703,
          targetId: 102,
          code: 'HD-DISPATCH',
          name: '调度管理部',
          isPrimary: true,
          effectiveStart: '2025-05-16 00:00:00',
          effectiveEnd: '',
          isCurrentlyEffective: true,
          status: 'ACTIVE',
          remarks: '主要组织',
          version: '3',
          updatedAt: '2026-06-11 10:12:18',
        },
      ],
      positions: [
        {
          id: 802,
          targetId: 201,
          code: 'DISPATCH-MGR',
          name: '调度经理',
          isPrimary: true,
          effectiveStart: '2025-05-16 00:00:00',
          effectiveEnd: '',
          isCurrentlyEffective: true,
          status: 'ACTIVE',
          remarks: '主要岗位',
          version: '3',
          updatedAt: '2026-06-11 10:13:40',
        },
      ],
      tenantMemberships: [
        {
          id: 302,
          tenantId: 7,
          tenantCode: 'LL-HUADONG',
          tenantName: '陆链华东运营中心',
          memberCode: 'HD00126',
          displayName: '顾敏',
          status: 'ACTIVE',
          isTenantAdmin: false,
          isCurrentlyEffective: true,
          membershipIsCurrentlyEffective: true,
          memberVersion: '4',
          joinedAt: '2025-05-16 00:00:00',
          leftAt: '',
          tenantStatus: 'ACTIVE',
          tenantIsDeleted: false,
          effectiveRange: '2025-05-16 ～ 长期有效',
          timezone: 'Asia/Shanghai',
        },
      ],
    },
    {
      id: 303,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      tenantName: '陆链华东运营中心',
      tenantTimezone: 'Asia/Shanghai',
      userId: 503,
      memberCode: 'HD00208',
      displayName: '沈拓',
      memberUserType: '正式员工',
      userName: 'shentuo',
      realName: '沈拓',
      nickName: '阿拓',
      phone: '137 0188 6120',
      email: 'shentuo@ll-east.cn',
      avatarUrl: '',
      globalUserType: '平台用户',
      userStatus: 'ACTIVE',
      memberStatus: 'ACTIVE',
      effectiveness: 'FUTURE',
      isTenantAdmin: false,
      isDefaultTenant: false,
      joinedAt: '2026-09-01 10:00:00',
      leftAt: '',
      primaryOrganization: '干线调度组',
      primaryPosition: '干线调度员',
      effectiveStart: '2026-10-01 00:00:00',
      effectiveEnd: '2027-09-30 23:59:59',
      effectiveRange: '2026-10-01 ～ 2027-09-30',
      remarks: '待项目启动后生效。',
      userRemarks: '干线调度人员。',
      version: '3',
      userVersion: '2',
      updatedAt: '2026-09-03 09:38:11',
      userUpdatedAt: '2026-09-01 10:00:00',
      organizations: [
        {
          id: 704,
          targetId: 104,
          code: 'HD-LINEHAUL',
          name: '干线调度组',
          isPrimary: true,
          effectiveStart: '2026-10-01 00:00:00',
          effectiveEnd: '2027-09-30 23:59:59',
          isCurrentlyEffective: false,
          status: 'ACTIVE',
          remarks: '未来生效',
          version: '1',
          updatedAt: '2026-09-03 09:38:11',
        },
      ],
      positions: [
        {
          id: 803,
          targetId: 202,
          code: 'LINEHAUL-DISPATCH',
          name: '干线调度员',
          isPrimary: true,
          effectiveStart: '2026-10-01 00:00:00',
          effectiveEnd: '2027-09-30 23:59:59',
          isCurrentlyEffective: false,
          status: 'ACTIVE',
          remarks: '未来生效',
          version: '1',
          updatedAt: '2026-09-03 09:38:11',
        },
      ],
      tenantMemberships: [
        {
          id: 303,
          tenantId: 7,
          tenantCode: 'LL-HUADONG',
          tenantName: '陆链华东运营中心',
          memberCode: 'HD00208',
          displayName: '沈拓',
          status: 'ACTIVE',
          isTenantAdmin: false,
          isCurrentlyEffective: false,
          membershipIsCurrentlyEffective: false,
          memberVersion: '2',
          joinedAt: '2026-10-01 00:00:00',
          leftAt: '2027-09-30 23:59:59',
          tenantStatus: 'ACTIVE',
          tenantIsDeleted: false,
          effectiveRange: '2026-10-01 ～ 2027-09-30',
          timezone: 'Asia/Shanghai',
        },
      ],
    },
    {
      id: 304,
      tenantId: 7,
      tenantCode: 'LL-HUADONG',
      tenantName: '陆链华东运营中心',
      tenantTimezone: 'Asia/Shanghai',
      userId: 504,
      memberCode: 'HD00061',
      displayName: '罗青',
      memberUserType: '外包人员',
      userName: 'luoqing',
      realName: '罗青',
      nickName: '罗工',
      phone: '136 0108 9021',
      email: 'luoqing@partner-logistics.cn',
      avatarUrl: '',
      globalUserType: '合作方用户',
      userStatus: 'ACTIVE',
      memberStatus: 'DISABLED',
      effectiveness: 'EXPIRED',
      isTenantAdmin: false,
      isDefaultTenant: false,
      joinedAt: '2024-03-01 08:30:00',
      leftAt: '2026-08-31 23:59:59',
      primaryOrganization: '车辆运营部',
      primaryPosition: '车队运营专员',
      effectiveStart: '2024-03-01 00:00:00',
      effectiveEnd: '2026-08-31 23:59:59',
      effectiveRange: '2024-03-01 ～ 2026-08-31',
      remarks: '外包服务已结束，保留历史关系。',
      userRemarks: '合作方外包人员。',
      version: '11',
      userVersion: '5',
      updatedAt: '2026-09-01 08:26:42',
      userUpdatedAt: '2026-08-31 17:12:03',
      organizations: [
        {
          id: 705,
          targetId: 103,
          code: 'HD-FLEET',
          name: '车辆运营部',
          isPrimary: true,
          effectiveStart: '2024-03-01 00:00:00',
          effectiveEnd: '2026-08-31 23:59:59',
          isCurrentlyEffective: false,
          status: 'DISABLED',
          remarks: '历史归属',
          version: '4',
          updatedAt: '2026-09-01 08:26:42',
        },
      ],
      positions: [
        {
          id: 804,
          targetId: 203,
          code: 'FLEET-SPECIALIST',
          name: '车队运营专员',
          isPrimary: true,
          effectiveStart: '2024-03-01 00:00:00',
          effectiveEnd: '2026-08-31 23:59:59',
          isCurrentlyEffective: false,
          status: 'DISABLED',
          remarks: '历史归属',
          version: '4',
          updatedAt: '2026-09-01 08:26:42',
        },
      ],
      tenantMemberships: [
        {
          id: 304,
          tenantId: 7,
          tenantCode: 'LL-HUADONG',
          tenantName: '陆链华东运营中心',
          memberCode: 'HD00061',
          displayName: '罗青',
          status: 'DISABLED',
          isTenantAdmin: false,
          isCurrentlyEffective: false,
          membershipIsCurrentlyEffective: false,
          memberVersion: '5',
          joinedAt: '2024-03-01 00:00:00',
          leftAt: '2026-08-31 23:59:59',
          tenantStatus: 'ACTIVE',
          tenantIsDeleted: false,
          effectiveRange: '2024-03-01 ～ 2026-08-31',
          timezone: 'Asia/Shanghai',
        },
      ],
    },
  ],
  tenantOptions: [
    {
      id: 3,
      code: 'HMXTSD',
      name: '汉明巡天山东',
      type: '企业租户',
      timezone: 'Asia/Shanghai',
      isDefault: false,
      accent: 'H',
    },
    {
      id: 7,
      code: 'LL-HUADONG',
      name: '陆链华东运营中心',
      type: '区域中心',
      timezone: 'Asia/Shanghai',
      isDefault: true,
      accent: '东',
    },
    {
      id: 9,
      code: 'LL-HUANAN',
      name: '陆链华南运营中心',
      type: '区域中心',
      timezone: 'Asia/Shanghai',
      isDefault: false,
      accent: '南',
    },
  ],
}
