import type { ApplicationRecord, PermissionResourceRecord } from '../types/applicationResources'

const audit = {
  canMaintain: true,
  version: '184000',
  createdAt: '2026-08-11T09:20:00+08:00',
  createdBy: 'bootstrap',
  updatedAt: '2026-09-08T10:28:00+08:00',
  updatedBy: 'hmxt',
}

function resource(
  value: Omit<PermissionResourceRecord, keyof typeof audit | 'children'> &
    Partial<Pick<PermissionResourceRecord, keyof typeof audit | 'children'>>,
): PermissionResourceRecord {
  return {
    ...audit,
    children: [],
    ...value,
  }
}

export const applicationResourcesFixture: ApplicationRecord[] = [
  {
    id: 1,
    appCode: 'IAM',
    appName: '身份与访问管理',
    description: '集团身份、组织、成员、角色与权限治理中心',
    icon: 'mdi:shield-account-outline',
    routePrefix: '/iam',
    status: 'active',
    remarks: '平台核心应用',
    ...audit,
    modules: [
      resource({
        id: 101,
        appId: 1,
        parentId: 0,
        resourceCode: 'IAM',
        resourceName: '身份与访问管理',
        resourceType: 'module',
        routePath: '',
        component: '',
        permissionCode: '',
        icon: 'mdi:shield-account-outline',
        httpMethod: '',
        apiPath: '',
        isVisible: false,
        sortOrder: 10,
        status: 'active',
        remarks: '创建 App 时自动生成的默认 Module',
        isCurrentlyEffective: true,
        invalidReason: '',
        children: [
          resource({
            id: 102,
            appId: 1,
            parentId: 101,
            resourceCode: 'IAM.APPLICATION_RESOURCES',
            resourceName: '应用与权限资源',
            resourceType: 'menu',
            routePath: '/iam/application-resources',
            component: 'iam/application-resources/pages/ApplicationResourcesPage',
            permissionCode: 'iam:application-resources:view',
            icon: 'mdi:layers-triple-outline',
            httpMethod: '',
            apiPath: '',
            isVisible: true,
            sortOrder: 20,
            status: 'active',
            remarks: '仅集团超级管理员可见',
            isCurrentlyEffective: true,
            invalidReason: '',
            children: [
              resource({
                id: 103,
                appId: 1,
                parentId: 102,
                resourceCode: 'IAM.APPLICATION_RESOURCES.CREATE',
                resourceName: '新增应用与资源',
                resourceType: 'function',
                routePath: '',
                component: '',
                permissionCode: 'iam:application-resources:create',
                icon: 'mdi:plus',
                httpMethod: 'POST',
                apiPath: '/iam-admin/AuthorizationCatalog/CreateResource',
                isVisible: false,
                sortOrder: 10,
                status: 'active',
                remarks: '新增权限资源功能',
                isCurrentlyEffective: true,
                invalidReason: '',
              }),
            ],
          }),
          resource({
            id: 104,
            appId: 1,
            parentId: 101,
            resourceCode: 'IAM.ROLES',
            resourceName: '角色管理',
            resourceType: 'menu',
            routePath: '/iam/roles',
            component: 'iam/access-control/pages/RoleManagementPage',
            permissionCode: 'iam:roles:view',
            icon: 'mdi:account-key-outline',
            httpMethod: '',
            apiPath: '',
            isVisible: true,
            sortOrder: 30,
            status: 'active',
            remarks: '',
            isCurrentlyEffective: true,
            invalidReason: '',
          }),
        ],
      }),
    ],
  },
  {
    id: 2,
    appCode: 'TMS',
    appName: '运输管理',
    description: '覆盖运输订单、调度、在途跟踪与运费结算',
    icon: 'mdi:routes',
    routePrefix: '/tms',
    status: 'active',
    remarks: '运输履约主应用',
    ...audit,
    version: '184012',
    modules: [
      resource({
        id: 201,
        appId: 2,
        parentId: 0,
        resourceCode: 'TMS',
        resourceName: '运输管理',
        resourceType: 'module',
        routePath: '',
        component: '',
        permissionCode: '',
        icon: 'mdi:routes',
        httpMethod: '',
        apiPath: '',
        isVisible: false,
        sortOrder: 10,
        status: 'active',
        remarks: '默认 Module',
        isCurrentlyEffective: true,
        invalidReason: '',
        version: '184021',
        children: [
          resource({
            id: 211,
            appId: 2,
            parentId: 201,
            resourceCode: 'TMS.ORDERS',
            resourceName: '运输订单',
            resourceType: 'menu',
            routePath: '/tms/orders',
            component: 'tms/orders/pages/OrderListPage',
            permissionCode: 'tms:orders:view',
            icon: 'mdi:clipboard-text-outline',
            httpMethod: '',
            apiPath: '',
            isVisible: true,
            sortOrder: 10,
            status: 'active',
            remarks: '运输订单列表与详情入口',
            isCurrentlyEffective: true,
            invalidReason: '',
            version: '184031',
            children: [
              resource({
                id: 212,
                appId: 2,
                parentId: 211,
                resourceCode: 'TMS.ORDERS.QUERY',
                resourceName: '查询运输订单',
                resourceType: 'function',
                routePath: '',
                component: '',
                permissionCode: 'tms:orders:query',
                icon: 'mdi:magnify',
                httpMethod: 'POST',
                apiPath: '/tms-admin/Order/Query',
                isVisible: false,
                sortOrder: 10,
                status: 'active',
                remarks: '',
                isCurrentlyEffective: true,
                invalidReason: '',
              }),
              resource({
                id: 213,
                appId: 2,
                parentId: 211,
                resourceCode: 'TMS.ORDERS.EXPORT',
                resourceName: '导出运输订单',
                resourceType: 'function',
                routePath: '',
                component: '',
                permissionCode: 'tms:orders:export',
                icon: 'mdi:tray-arrow-down',
                httpMethod: 'POST',
                apiPath: '/tms-admin/Order/Export',
                isVisible: false,
                sortOrder: 20,
                status: 'disabled',
                remarks: '等待新导出任务服务启用',
                isCurrentlyEffective: false,
                invalidReason: '资源自身已停用',
              }),
            ],
          }),
          resource({
            id: 221,
            appId: 2,
            parentId: 201,
            resourceCode: 'TMS.DISPATCH',
            resourceName: '运输调度',
            resourceType: 'menu',
            routePath: '/tms/dispatch',
            component: 'tms/dispatch/pages/DispatchWorkbenchPage',
            permissionCode: 'tms:dispatch:view',
            icon: 'mdi:map-marker-path',
            httpMethod: '',
            apiPath: '',
            isVisible: true,
            sortOrder: 20,
            status: 'active',
            remarks: '调度工作台入口',
            isCurrentlyEffective: true,
            invalidReason: '',
            children: [
              resource({
                id: 222,
                appId: 2,
                parentId: 221,
                resourceCode: 'TMS.DISPATCH.ASSIGN',
                resourceName: '分配车辆与司机',
                resourceType: 'function',
                routePath: '',
                component: '',
                permissionCode: 'tms:dispatch:assign',
                icon: 'mdi:wrench-outline',
                httpMethod: 'POST',
                apiPath: '/tms-admin/Dispatch/Assign',
                isVisible: false,
                sortOrder: 10,
                status: 'active',
                remarks: '',
                isCurrentlyEffective: true,
                invalidReason: '',
              }),
            ],
          }),
        ],
      }),
      resource({
        id: 230,
        appId: 2,
        parentId: 0,
        resourceCode: 'TMS.SETTLEMENT',
        resourceName: '运输结算',
        resourceType: 'module',
        routePath: '',
        component: '',
        permissionCode: '',
        icon: 'mdi:cash-multiple',
        httpMethod: '',
        apiPath: '',
        isVisible: false,
        sortOrder: 20,
        status: 'active',
        remarks: '普通 Module',
        isCurrentlyEffective: true,
        invalidReason: '',
      }),
    ],
  },
  {
    id: 3,
    appCode: 'VMS',
    appName: '车辆管理',
    description: '车辆、司机和车队基础资料管理',
    icon: 'mdi:car-cog',
    routePrefix: '/vms',
    status: 'disabled',
    remarks: '维护窗口内暂时停用',
    ...audit,
    version: '184042',
    modules: [
      resource({
        id: 301,
        appId: 3,
        parentId: 0,
        resourceCode: 'VMS',
        resourceName: '车辆管理',
        resourceType: 'module',
        routePath: '',
        component: '',
        permissionCode: '',
        icon: 'mdi:car-cog',
        httpMethod: '',
        apiPath: '',
        isVisible: false,
        sortOrder: 10,
        status: 'active',
        remarks: '默认 Module',
        isCurrentlyEffective: false,
        invalidReason: '所属 App 已停用',
        children: [
          resource({
            id: 302,
            appId: 3,
            parentId: 301,
            resourceCode: 'VMS.VEHICLES',
            resourceName: '车辆档案',
            resourceType: 'menu',
            routePath: '/vms/vehicles',
            component: 'vms/vehicles/pages/VehicleListPage',
            permissionCode: 'vms:vehicles:view',
            icon: 'mdi:car-cog',
            httpMethod: '',
            apiPath: '',
            isVisible: true,
            sortOrder: 10,
            status: 'active',
            remarks: '',
            isCurrentlyEffective: false,
            invalidReason: '所属 App 已停用',
          }),
        ],
      }),
    ],
  },
]
