import type { TrainingContentFixture } from '../types/trainingContent'

export const trainingContentFixture: TrainingContentFixture = {
  courses: [
    {
      id: 1001,
      name: '危化品道路运输安全基础',
      trainingType: '岗前必修',
      description: '面向危化品运输驾驶员与押运员的基础安全课程，覆盖装卸、行车和突发事件处置。',
      videoFileName: 'hazmat-safety-basics-v3.mp4',
      videoSize: '428 MB',
      videoDurationSeconds: 2700,
      plannedDurationSeconds: 2700,
      status: 'ACTIVE',
      isLocked: true,
      createdAt: '2026-08-18 09:12:40',
      createdBy: 'training.admin',
      updatedAt: '2026-09-13 16:42:18',
      updatedBy: 'safety.manager',
      version: '18',
    },
    {
      id: 1002,
      name: '车辆日常检查与故障上报',
      trainingType: '年度复训',
      description: '规范出车前、行车中和收车后的车辆检查动作与故障闭环。',
      videoFileName: 'vehicle-inspection-2026.mp4',
      videoSize: '312 MB',
      videoDurationSeconds: 2100,
      plannedDurationSeconds: 2100,
      status: 'ACTIVE',
      isLocked: false,
      createdAt: '2026-08-22 10:08:16',
      createdBy: 'training.admin',
      updatedAt: '2026-09-12 11:24:09',
      updatedBy: 'training.admin',
      version: '9',
    },
    {
      id: 1003,
      name: '长途驾驶疲劳风险识别',
      trainingType: '专项培训',
      description: '帮助驾驶员识别疲劳信号并执行休息与换班要求。',
      videoFileName: 'fatigue-risk-draft.mp4',
      videoSize: '186 MB',
      videoDurationSeconds: 1320,
      plannedDurationSeconds: 1320,
      status: 'DRAFT',
      isLocked: false,
      createdAt: '2026-09-08 14:30:00',
      createdBy: 'safety.manager',
      updatedAt: '2026-09-14 09:15:36',
      updatedBy: 'safety.manager',
      version: '3',
    },
    {
      id: 1004,
      name: '雨雪天气运输风险控制',
      trainingType: '季节专题',
      description: '冬季雨雪天气下的车辆准备、驾驶策略和异常上报。',
      videoFileName: 'winter-driving-2025.mp4',
      videoSize: '256 MB',
      videoDurationSeconds: 1680,
      plannedDurationSeconds: 1680,
      status: 'DISABLED',
      isLocked: false,
      createdAt: '2025-10-15 08:40:20',
      createdBy: 'training.admin',
      updatedAt: '2026-04-02 13:28:11',
      updatedBy: 'training.admin',
      version: '12',
    },
  ],
  questions: [
    {
      id: 2101,
      stem: '运输危化品车辆出车前，驾驶员首先应确认哪一项？',
      type: 'SINGLE_CHOICE',
      options: [
        { label: 'A', content: '车辆与运输介质相关资质、随车文件有效', isCorrect: true, order: 1 },
        { label: 'B', content: '只检查燃油是否充足', isCorrect: false, order: 2 },
        { label: 'C', content: '先发车，途中再补做检查', isCorrect: false, order: 3 },
        { label: 'D', content: '仅由押运员口头确认', isCorrect: false, order: 4 },
      ],
      analysis: '危化品运输必须先完成车辆、人员、介质和随车文件的完整核验。',
      status: 'ACTIVE',
      createdAt: '2026-08-19 10:16:20',
      createdBy: 'training.admin',
      updatedAt: '2026-09-12 15:22:11',
      updatedBy: 'safety.manager',
      version: '7',
    },
    {
      id: 2102,
      stem: '发现制动系统存在异常时，驾驶员可以采取哪些措施？',
      type: 'MULTIPLE_CHOICE',
      options: [
        { label: 'A', content: '立即停止出车或选择安全区域停车', isCorrect: true, order: 1 },
        { label: 'B', content: '按流程上报并等待维修确认', isCorrect: true, order: 2 },
        { label: 'C', content: '低速继续执行运输任务', isCorrect: false, order: 3 },
        { label: 'D', content: '记录故障现象和车辆状态', isCorrect: true, order: 4 },
      ],
      analysis: '制动异常属于影响行车安全的重大故障，应停止运行、上报并保留记录。',
      status: 'ACTIVE',
      createdAt: '2026-08-23 09:08:42',
      createdBy: 'training.admin',
      updatedAt: '2026-09-11 10:45:08',
      updatedBy: 'training.admin',
      version: '5',
    },
    {
      id: 2103,
      stem: '连续驾驶达到规定时长后，应进入服务区或安全地点休息。',
      type: 'TRUE_FALSE',
      options: [
        { label: 'A', content: '正确', isCorrect: true, order: 1 },
        { label: 'B', content: '错误', isCorrect: false, order: 2 },
      ],
      analysis: '驾驶员必须遵守连续驾驶时长和强制休息要求。',
      status: 'ACTIVE',
      createdAt: '2026-08-26 16:20:18',
      createdBy: 'safety.manager',
      updatedAt: '2026-09-10 17:12:02',
      updatedBy: 'safety.manager',
      version: '4',
    },
    {
      id: 2104,
      stem: '雨雪天气进入弯道路段前，应如何调整车辆状态？',
      type: 'SINGLE_CHOICE',
      options: [
        { label: 'A', content: '提前减速并保持更大安全距离', isCorrect: true, order: 1 },
        { label: 'B', content: '进入弯道后紧急制动', isCorrect: false, order: 2 },
        { label: 'C', content: '加速快速通过弯道', isCorrect: false, order: 3 },
      ],
      analysis: '应在进入弯道前完成减速，避免弯道内急刹导致侧滑。',
      status: 'DRAFT',
      createdAt: '2026-09-10 11:30:00',
      createdBy: 'safety.manager',
      updatedAt: '2026-09-14 10:26:48',
      updatedBy: 'safety.manager',
      version: '2',
    },
  ],
  papers: [
    {
      id: 3101,
      name: '危化品驾驶员岗前安全考试 A 卷',
      description: '用于危化品驾驶员首次上岗前的知识与处置能力验证。',
      mode: 'FIXED',
      totalScore: 100,
      status: 'ACTIVE',
      randomizeQuestionOrder: true,
      randomizeOptionOrder: true,
      fixedQuestions: [
        {
          questionId: 2101,
          stem: '运输危化品车辆出车前，驾驶员首先应确认哪一项？',
          type: 'SINGLE_CHOICE',
          status: 'ACTIVE',
          score: 30,
          order: 1,
        },
        {
          questionId: 2102,
          stem: '发现制动系统存在异常时，驾驶员可以采取哪些措施？',
          type: 'MULTIPLE_CHOICE',
          status: 'ACTIVE',
          score: 40,
          order: 2,
        },
        {
          questionId: 2103,
          stem: '连续驾驶达到规定时长后，应进入服务区或安全地点休息。',
          type: 'TRUE_FALSE',
          status: 'ACTIVE',
          score: 30,
          order: 3,
        },
      ],
      randomRules: [],
      createdAt: '2026-08-28 10:12:00',
      createdBy: 'training.admin',
      updatedAt: '2026-09-12 09:22:35',
      updatedBy: 'training.admin',
      version: '8',
    },
    {
      id: 3102,
      name: '年度安全复训随机卷',
      description: '按题型随机抽取题目，覆盖车辆检查、道路风险和应急处置。',
      mode: 'RANDOM',
      totalScore: 100,
      status: 'ACTIVE',
      randomizeQuestionOrder: true,
      randomizeOptionOrder: true,
      fixedQuestions: [],
      randomRules: [
        { type: 'SINGLE_CHOICE', count: 10, scorePerQuestion: 4, availableCount: 86 },
        { type: 'MULTIPLE_CHOICE', count: 6, scorePerQuestion: 6, availableCount: 42 },
        { type: 'TRUE_FALSE', count: 6, scorePerQuestion: 4, availableCount: 58 },
      ],
      createdAt: '2026-08-30 13:05:18',
      createdBy: 'safety.manager',
      updatedAt: '2026-09-13 14:08:51',
      updatedBy: 'safety.manager',
      version: '6',
    },
    {
      id: 3103,
      name: '冬季运输专项测验',
      description: '冬季课程配套测验，待安全部门复核后启用。',
      mode: 'FIXED',
      totalScore: 60,
      status: 'DRAFT',
      randomizeQuestionOrder: false,
      randomizeOptionOrder: false,
      fixedQuestions: [
        {
          questionId: 2104,
          stem: '雨雪天气进入弯道路段前，应如何调整车辆状态？',
          type: 'SINGLE_CHOICE',
          status: 'DRAFT',
          score: 20,
          order: 1,
        },
      ],
      randomRules: [],
      createdAt: '2026-09-10 09:20:00',
      createdBy: 'training.admin',
      updatedAt: '2026-09-14 08:32:14',
      updatedBy: 'training.admin',
      version: '2',
    },
  ],
  examConfigurations: [
    {
      id: 4101,
      name: '危化品驾驶员岗前考试规则',
      description: '岗前考试最多 3 次，达到 80 分视为通过。',
      paperId: 3101,
      paperName: '危化品驾驶员岗前安全考试 A 卷',
      paperMode: 'FIXED',
      paperStatus: 'ACTIVE',
      paperTotalScore: 100,
      durationSeconds: 3600,
      passScore: 80,
      maxAttempts: 3,
      showCorrectAnswer: true,
      showAnswerAnalysis: false,
      status: 'ACTIVE',
      createdAt: '2026-08-29 09:45:00',
      createdBy: 'training.admin',
      updatedAt: '2026-09-13 17:05:22',
      updatedBy: 'safety.manager',
      version: '7',
    },
    {
      id: 4102,
      name: '年度复训统一考试规则',
      description: '年度复训采用随机卷，允许 2 次考试。',
      paperId: 3102,
      paperName: '年度安全复训随机卷',
      paperMode: 'RANDOM',
      paperStatus: 'ACTIVE',
      paperTotalScore: 100,
      durationSeconds: 2700,
      passScore: 75,
      maxAttempts: 2,
      showCorrectAnswer: false,
      showAnswerAnalysis: false,
      status: 'ACTIVE',
      createdAt: '2026-09-01 14:20:18',
      createdBy: 'safety.manager',
      updatedAt: '2026-09-12 11:18:06',
      updatedBy: 'safety.manager',
      version: '4',
    },
    {
      id: 4103,
      name: '冬季专项测验规则',
      description: '待试卷完成后启用。',
      paperId: 3103,
      paperName: '冬季运输专项测验',
      paperMode: 'FIXED',
      paperStatus: 'DRAFT',
      paperTotalScore: 60,
      durationSeconds: 1800,
      passScore: 48,
      maxAttempts: 3,
      showCorrectAnswer: false,
      showAnswerAnalysis: false,
      status: 'DRAFT',
      createdAt: '2026-09-10 10:05:00',
      createdBy: 'training.admin',
      updatedAt: '2026-09-14 08:40:20',
      updatedBy: 'training.admin',
      version: '2',
    },
  ],
}
